import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JTextField;
import javax.swing.*;
import java.awt.*; 
import java.text.DecimalFormat;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 5678m
 */
public class AutoLoanCalculator extends javax.swing.JFrame {
    /**
     * Creates new form AutoLoanCalculator
     */
    public AutoLoanCalculator() {
        initComponents();
        
        jPanel2.setBackground(new Color(66,133,244,80));
        jPanel4.setBackground(new Color(66,133,244,80));
        panelRound1.setBackground(new Color(66,133,244,80));
        
        autoPriceTextField.setBackground(new Color(66,133,244,40));
        autoPriceTextField.setOpaque(false);
        loanTermTextField.setBackground(new Color(66,133,244,80));
        loanTermTextField.setOpaque(false);
        interestRateTextField.setBackground(new Color(66,133,244,40));
        interestRateTextField.setOpaque(false);
        cashIncentivesTextField.setBackground(new Color(66,133,244,80));
        cashIncentivesTextField.setOpaque(false);
        downPaymentTextField.setBackground(new Color(66,133,244,40));
        downPaymentTextField.setOpaque(false);
        tradeInValueTextField.setBackground(new Color(66,133,244,80));
        tradeInValueTextField.setOpaque(false);
        amtOwedOnTradeInTextField.setBackground(new Color(66,133,244,40));
        amtOwedOnTradeInTextField.setOpaque(false);
        salesTaxTextField.setBackground(new Color(66,133,244,80));
        salesTaxTextField.setOpaque(false);
        otherFeesTextField.setBackground(new Color(66,133,244,40));
        otherFeesTextField.setOpaque(false);
        
        
        imageLabel.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("images/CapitalLogo.png")).getImage().getScaledInstance(166,80,Image.SCALE_SMOOTH)));
        quitLabel.setHorizontalAlignment(JLabel.CENTER);
        calculateLabel.setHorizontalAlignment(JLabel.CENTER);
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        apLabel = new javax.swing.JLabel();
        ltLabel = new javax.swing.JLabel();
        irLabel = new javax.swing.JLabel();
        ciLabel = new javax.swing.JLabel();
        dpLabel = new javax.swing.JLabel();
        tivLabel = new javax.swing.JLabel();
        aotLabel = new javax.swing.JLabel();
        stLabel = new javax.swing.JLabel();
        ofLabel = new javax.swing.JLabel();
        autoPriceTextField = new javax.swing.JTextField();
        loanTermTextField = new javax.swing.JTextField();
        interestRateTextField = new javax.swing.JTextField();
        cashIncentivesTextField = new javax.swing.JTextField();
        downPaymentTextField = new javax.swing.JTextField();
        tradeInValueTextField = new javax.swing.JTextField();
        amtOwedOnTradeInTextField = new javax.swing.JTextField();
        salesTaxTextField = new javax.swing.JTextField();
        otherFeesTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelRound1 = new PanelRound();
        mpLabel = new javax.swing.JLabel();
        tlaLabel = new javax.swing.JLabel();
        tstLabel = new javax.swing.JLabel();
        ufpLabel = new javax.swing.JLabel();
        tlpLabel = new javax.swing.JLabel();
        tliLabel = new javax.swing.JLabel();
        tcLabel = new javax.swing.JLabel();
        monthlyPaymentLabel = new javax.swing.JLabel();
        totalLoanAmountLabel = new javax.swing.JLabel();
        salesTaxLabel = new javax.swing.JLabel();
        upfrontPaymentLabel = new javax.swing.JLabel();
        totalLoanPaymentLabel = new javax.swing.JLabel();
        totalLoanInterestLabel = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();
        panelRound2 = new PanelRound();
        calculateLabel = new javax.swing.JLabel();
        includeAllFees = new javax.swing.JCheckBox();
        panelRound3 = new PanelRound();
        quitLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        formTitleLabel = new javax.swing.JLabel();
        XBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1135, 850));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(66, 133, 242));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Auto Loan Calculator");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 124, -1, -1));

        apLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apLabel.setForeground(new java.awt.Color(102, 102, 102));
        apLabel.setText("Auto Price ($):");
        jPanel1.add(apLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 281, -1, 38));

        ltLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ltLabel.setForeground(new java.awt.Color(102, 102, 102));
        ltLabel.setText("Loan Term (months):");
        jPanel1.add(ltLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 337, -1, 38));

        irLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        irLabel.setForeground(new java.awt.Color(102, 102, 102));
        irLabel.setText("Interest Rate (%):");
        jPanel1.add(irLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 393, -1, 38));

        ciLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ciLabel.setForeground(new java.awt.Color(102, 102, 102));
        ciLabel.setText("Cash Incentives ($):");
        jPanel1.add(ciLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 449, -1, 38));

        dpLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dpLabel.setForeground(new java.awt.Color(102, 102, 102));
        dpLabel.setText("Down Payment ($):");
        jPanel1.add(dpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 505, -1, 38));

        tivLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tivLabel.setForeground(new java.awt.Color(102, 102, 102));
        tivLabel.setText("Trade-In Value ($):");
        jPanel1.add(tivLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 561, -1, 38));

        aotLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aotLabel.setForeground(new java.awt.Color(102, 102, 102));
        aotLabel.setText("Amount Owed On Trade-In ($):");
        jPanel1.add(aotLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, 38));

        stLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stLabel.setForeground(new java.awt.Color(102, 102, 102));
        stLabel.setText("Sales Tax (%):");
        jPanel1.add(stLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, -1, 38));

        ofLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ofLabel.setForeground(new java.awt.Color(102, 102, 102));
        ofLabel.setText("Other Fees ($):");
        jPanel1.add(ofLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 730, -1, 38));

        autoPriceTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        autoPriceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                autoPriceTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(autoPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 281, 182, 38));

        loanTermTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loanTermTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loanTermTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(loanTermTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 337, 182, 38));

        interestRateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        interestRateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                interestRateTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(interestRateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 393, 182, 38));

        cashIncentivesTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashIncentivesTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashIncentivesTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(cashIncentivesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 449, 182, 38));

        downPaymentTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        downPaymentTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                downPaymentTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(downPaymentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 505, 182, 38));

        tradeInValueTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tradeInValueTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tradeInValueTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(tradeInValueTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 561, 182, 38));

        amtOwedOnTradeInTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amtOwedOnTradeInTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amtOwedOnTradeInTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(amtOwedOnTradeInTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 182, 38));

        salesTaxTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salesTaxTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salesTaxTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(salesTaxTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 670, 182, 38));

        otherFeesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherFeesTextFieldActionPerformed(evt);
            }
        });
        otherFeesTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otherFeesTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(otherFeesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 730, 182, 38));

        jPanel4.setBackground(new java.awt.Color(66, 133, 244));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Results");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 124, -1, -1));

        panelRound1.setBackground(new java.awt.Color(66, 133, 244));
        panelRound1.setRoundButtomLeft(50);
        panelRound1.setRoundButtomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        mpLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mpLabel.setText("Monthly Payment:");

        tlaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tlaLabel.setText("Total Loan Amount:");

        tstLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tstLabel.setText("Sales Tax:");

        ufpLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ufpLabel.setText("Upfront Payment:");

        tlpLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tlpLabel.setText("Total Loan Payment:");

        tliLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tliLabel.setText("Total Loan Interest:");

        tcLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tcLabel.setText("Total Cost:");

        monthlyPaymentLabel.setBackground(new java.awt.Color(255, 255, 255));
        monthlyPaymentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthlyPaymentLabel.setForeground(new java.awt.Color(102, 102, 102));
        monthlyPaymentLabel.setOpaque(true);

        totalLoanAmountLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalLoanAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalLoanAmountLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalLoanAmountLabel.setToolTipText("");
        totalLoanAmountLabel.setOpaque(true);

        salesTaxLabel.setBackground(new java.awt.Color(255, 255, 255));
        salesTaxLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salesTaxLabel.setForeground(new java.awt.Color(102, 102, 102));
        salesTaxLabel.setOpaque(true);

        upfrontPaymentLabel.setBackground(new java.awt.Color(255, 255, 255));
        upfrontPaymentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        upfrontPaymentLabel.setForeground(new java.awt.Color(102, 102, 102));
        upfrontPaymentLabel.setOpaque(true);

        totalLoanPaymentLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalLoanPaymentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalLoanPaymentLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalLoanPaymentLabel.setOpaque(true);

        totalLoanInterestLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalLoanInterestLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalLoanInterestLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalLoanInterestLabel.setOpaque(true);

        totalCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalCostLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalCostLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalCostLabel.setOpaque(true);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mpLabel)
                    .addComponent(tlaLabel)
                    .addComponent(tstLabel)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tlpLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ufpLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tliLabel)
                    .addComponent(tcLabel))
                .addGap(72, 72, 72)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monthlyPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(totalLoanAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesTaxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upfrontPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalLoanPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalLoanInterestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mpLabel)
                            .addComponent(monthlyPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(tlaLabel))
                    .addComponent(totalLoanAmountLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tstLabel)
                    .addComponent(salesTaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ufpLabel)
                    .addComponent(upfrontPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tlpLabel)
                    .addComponent(totalLoanPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tliLabel)
                    .addComponent(totalLoanInterestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tcLabel)
                    .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 250, -1, -1));

        panelRound2.setBackground(new java.awt.Color(66, 133, 244));
        panelRound2.setRoundButtomLeft(25);
        panelRound2.setRoundButtomRight(25);
        panelRound2.setRoundTopLeft(25);
        panelRound2.setRoundTopRight(25);

        calculateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculateLabel.setForeground(new java.awt.Color(255, 255, 255));
        calculateLabel.setText("Calculate");
        calculateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calculateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 626, -1, -1));

        includeAllFees.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        includeAllFees.setText("Include All Fees");
        jPanel1.add(includeAllFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 584, -1, -1));

        panelRound3.setBackground(new java.awt.Color(66, 133, 244));
        panelRound3.setRoundButtomLeft(25);
        panelRound3.setRoundButtomRight(25);
        panelRound3.setRoundTopLeft(25);
        panelRound3.setRoundTopRight(25);

        quitLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quitLabel.setForeground(new java.awt.Color(255, 255, 255));
        quitLabel.setText("Quit");
        quitLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 694, -1, -1));

        jPanel3.setBackground(new java.awt.Color(66, 133, 244));

        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
        });

        formTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        formTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        formTitleLabel.setText("Capital Cal");
        formTitleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formTitleLabelMouseClicked(evt);
            }
        });

        XBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        XBtn.setForeground(new java.awt.Color(255, 51, 51));
        XBtn.setText("X");
        XBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        XBtn.setFocusPainted(false);
        XBtn.setPreferredSize(new java.awt.Dimension(43, 43));
        XBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(XBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(formTitleLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(XBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1135, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateLabelMouseClicked
        // TODO add your handling code here:
        String autoPriceStr = autoPriceTextField.getText().trim();
        String loanTermStr = loanTermTextField.getText().trim();
        String interestRateStr = interestRateTextField.getText().trim();
        String cashIncentivesStr = cashIncentivesTextField.getText().trim();
        String downPaymentStr = downPaymentTextField.getText().trim();
        String tradeInValueStr = tradeInValueTextField.getText().trim();
        String amtOwedOnTradeStr = amtOwedOnTradeInTextField.getText().trim();
        String salesTaxStr = salesTaxTextField.getText().trim();
        String otherFeesStr = otherFeesTextField.getText().trim();
        
        if (!Helper.validateAllInputs(autoPriceStr, loanTermStr, interestRateStr, cashIncentivesStr, downPaymentStr, tradeInValueStr, amtOwedOnTradeStr, salesTaxStr, otherFeesStr)) {
            autoPriceTextField.requestFocus();
            return;
        }
        
        double autoPrice = Double.parseDouble(autoPriceTextField.getText());
        int loanTerm = Integer.parseInt(loanTermTextField.getText());
        //double loanTerm = Double.parseDouble(loanTermTextField.getText());
        double interestRate = Double.parseDouble(interestRateTextField.getText());
        double cashIncentives = Double.parseDouble(cashIncentivesTextField.getText());
        double downPayment = Double.parseDouble(downPaymentTextField.getText());
        double tradeInValue = Double.parseDouble(tradeInValueTextField.getText());
        double amtOwedOnTradeIn = Double.parseDouble(amtOwedOnTradeInTextField.getText());
        double salesTax = Double.parseDouble(salesTaxTextField.getText());
        double otherFees = Double.parseDouble(otherFeesTextField.getText());
        
        double[] theMonthlyPayment;
        if(includeAllFees.isSelected()){
            theMonthlyPayment = Helper.autoLoanCalculatorWithFees(autoPrice, loanTerm, interestRate, cashIncentives, downPayment, tradeInValue, amtOwedOnTradeIn, salesTax, otherFees);
            for (double value : theMonthlyPayment) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        autoPriceTextField.requestFocus();
                        return;
                    }
                }
            
            double realMonthlyPayment = theMonthlyPayment[0];
            double realLoanAmount = theMonthlyPayment[1];
            double realSalesTax = theMonthlyPayment[2];
            double realUpPayment = theMonthlyPayment[3];
            double realLoanPayment = theMonthlyPayment[4];
            double realLoanInterest = theMonthlyPayment[5];
            double realTotalCost = theMonthlyPayment[6];
            
            DecimalFormat formatter = new DecimalFormat("#,###.00");
            monthlyPaymentLabel.setText("$" + formatter.format(realMonthlyPayment));
            totalLoanAmountLabel.setText("$" + formatter.format(realLoanAmount));
            salesTaxLabel.setText("$" + formatter.format(realSalesTax));
            upfrontPaymentLabel.setText("$" + formatter.format(realUpPayment));
            totalLoanPaymentLabel.setText("$" + formatter.format(realLoanPayment));
            totalLoanInterestLabel.setText("$" + formatter.format(realLoanInterest));
            totalCostLabel.setText("$" + formatter.format(realTotalCost));


        }else{
            theMonthlyPayment = Helper.autoLoanCalculatorWithoutFee(autoPrice, loanTerm, interestRate, cashIncentives, downPayment, tradeInValue, amtOwedOnTradeIn, salesTax, otherFees);
            for (double value : theMonthlyPayment) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        autoPriceTextField.requestFocus();
                        return;
                    }
                }
            
            double realMonthlyPayment = theMonthlyPayment[0];
            double realLoanAmount = theMonthlyPayment[1];
            double realSalesTax = theMonthlyPayment[2];
            double realUpPayment = theMonthlyPayment[3];
            double realLoanPayment = theMonthlyPayment[4];
            double realLoanInterest = theMonthlyPayment[5];
            double realTotalCost = theMonthlyPayment[6];
            
            DecimalFormat formatter = new DecimalFormat("#,###.00");
            monthlyPaymentLabel.setText("$" + formatter.format(realMonthlyPayment));
            totalLoanAmountLabel.setText("$" + formatter.format(realLoanAmount));
            salesTaxLabel.setText("$" + formatter.format(realSalesTax));
            upfrontPaymentLabel.setText("$" + formatter.format(realUpPayment));
            totalLoanPaymentLabel.setText("$" + formatter.format(realLoanPayment));
            totalLoanInterestLabel.setText("$" + formatter.format(realLoanInterest));
            totalCostLabel.setText("$" + formatter.format(realTotalCost));
        }
    }//GEN-LAST:event_calculateLabelMouseClicked

    private void autoPriceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_autoPriceTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(autoPriceTextField, evt);
    }//GEN-LAST:event_autoPriceTextFieldKeyTyped

    private void loanTermTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanTermTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateSingleInput(loanTermTextField, evt);
    }//GEN-LAST:event_loanTermTextFieldKeyTyped

    private void interestRateTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_interestRateTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(interestRateTextField, evt);
    }//GEN-LAST:event_interestRateTextFieldKeyTyped

    private void cashIncentivesTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashIncentivesTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(cashIncentivesTextField, evt);
    }//GEN-LAST:event_cashIncentivesTextFieldKeyTyped

    private void downPaymentTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_downPaymentTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(downPaymentTextField, evt);
    }//GEN-LAST:event_downPaymentTextFieldKeyTyped

    private void tradeInValueTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tradeInValueTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(tradeInValueTextField, evt);
    }//GEN-LAST:event_tradeInValueTextFieldKeyTyped

    private void amtOwedOnTradeInTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amtOwedOnTradeInTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(amtOwedOnTradeInTextField, evt);
    }//GEN-LAST:event_amtOwedOnTradeInTextFieldKeyTyped

    private void salesTaxTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salesTaxTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(salesTaxTextField, evt);
    }//GEN-LAST:event_salesTaxTextFieldKeyTyped

    private void otherFeesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherFeesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherFeesTextFieldActionPerformed

    private void otherFeesTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherFeesTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(otherFeesTextField, evt);
    }//GEN-LAST:event_otherFeesTextFieldKeyTyped

    private void quitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quitLabelMouseClicked

    private void XBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_XBtnMouseClicked

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked
        calcPage4_misc calc4 = new calcPage4_misc();
        calc4.setSize(1650, 1800);
        calc4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imageLabelMouseClicked

    private void formTitleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formTitleLabelMouseClicked
        calcPage4_misc calc4 = new calcPage4_misc();
        calc4.setSize(1650, 1800);
        calc4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formTitleLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoLoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoLoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoLoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoLoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoLoanCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XBtn;
    private javax.swing.JTextField amtOwedOnTradeInTextField;
    private javax.swing.JLabel aotLabel;
    private javax.swing.JLabel apLabel;
    private javax.swing.JTextField autoPriceTextField;
    private javax.swing.JLabel calculateLabel;
    private javax.swing.JTextField cashIncentivesTextField;
    private javax.swing.JLabel ciLabel;
    private javax.swing.JTextField downPaymentTextField;
    private javax.swing.JLabel dpLabel;
    private javax.swing.JLabel formTitleLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JCheckBox includeAllFees;
    private javax.swing.JTextField interestRateTextField;
    private javax.swing.JLabel irLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField loanTermTextField;
    private javax.swing.JLabel ltLabel;
    private javax.swing.JLabel monthlyPaymentLabel;
    private javax.swing.JLabel mpLabel;
    private javax.swing.JLabel ofLabel;
    private javax.swing.JTextField otherFeesTextField;
    private PanelRound panelRound1;
    private PanelRound panelRound2;
    private PanelRound panelRound3;
    private javax.swing.JLabel quitLabel;
    private javax.swing.JLabel salesTaxLabel;
    private javax.swing.JTextField salesTaxTextField;
    private javax.swing.JLabel stLabel;
    private javax.swing.JLabel tcLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel tivLabel;
    private javax.swing.JLabel tlaLabel;
    private javax.swing.JLabel tliLabel;
    private javax.swing.JLabel tlpLabel;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JLabel totalLoanAmountLabel;
    private javax.swing.JLabel totalLoanInterestLabel;
    private javax.swing.JLabel totalLoanPaymentLabel;
    private javax.swing.JTextField tradeInValueTextField;
    private javax.swing.JLabel tstLabel;
    private javax.swing.JLabel ufpLabel;
    private javax.swing.JLabel upfrontPaymentLabel;
    // End of variables declaration//GEN-END:variables
}
