/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.util.Dictionary;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author loved
 */

// TODOS:
/*
    Validate inputs for nonzero doubles only
    Add USD to currencies
    Commas and decimals
    Dict of currency symbols
    Option for top 10 most popular currencies
    Fixed horizontal length and line wrapping for text boxes
*/


public class currency_calc extends javax.swing.JFrame {

    /**
     * Creates new form currency_calc
     */
    Map<String, Double> conversionTable = Helper.webScraper();
    public currency_calc() {
        initComponents();
        errLabel.setVisible(false);
        
        // Making a dictionary to hold the webscraped currencies and their exchange rates
        // Adding them to the two combo boxes
        //Map<String, Double> conversionTable = Helper.webScraper();
        System.out.println("\n" + conversionTable.get("Euro"));
        DefaultComboBoxModel<String> comboModel1 = new DefaultComboBoxModel <String>();
        DefaultComboBoxModel<String> comboModel2 = new DefaultComboBoxModel <String>();
        for (String key : conversionTable.keySet()){
            comboModel1.addElement(key);
            comboModel2.addElement(key);
        }
        oldCurrDrop.setModel(comboModel1);
        newCurrDrop.setModel(comboModel2);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oldCurrDrop = new javax.swing.JComboBox<>();
        newCurrDrop = new javax.swing.JComboBox<>();
        newCurrAmt = new javax.swing.JLabel();
        oldCurrAmt = new javax.swing.JTextField();
        errLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        oldCurrDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        oldCurrDrop.setName(""); // NOI18N
        oldCurrDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldCurrDropActionPerformed(evt);
            }
        });

        newCurrDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        newCurrDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCurrDropActionPerformed(evt);
            }
        });

        newCurrAmt.setBackground(new java.awt.Color(255, 255, 255));
        newCurrAmt.setText("0");

        oldCurrAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldCurrAmtActionPerformed(evt);
            }
        });

        errLabel.setForeground(new java.awt.Color(255, 51, 51));
        errLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errLabel.setText("N/A");
        errLabel.setAlignmentX(0.5F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oldCurrDrop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oldCurrAmt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newCurrAmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newCurrDrop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(errLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldCurrDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCurrDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCurrAmt)
                    .addComponent(oldCurrAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldCurrDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldCurrDropActionPerformed
        currencyValidate();
    }//GEN-LAST:event_oldCurrDropActionPerformed

    private void newCurrDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCurrDropActionPerformed
        currencyValidate();
    }//GEN-LAST:event_newCurrDropActionPerformed

    private void oldCurrAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldCurrAmtActionPerformed
        currencyValidate();
    }//GEN-LAST:event_oldCurrAmtActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public Double convert(){
        // oldCurr to USD
        Double newCurr = Double.valueOf(oldCurrAmt.getText()) / conversionTable.get(String.valueOf(oldCurrDrop.getSelectedItem()));
        // USD to newCurr
        //System.out.println(String.valueOf(newCurr));
        newCurr *= conversionTable.get(String.valueOf(newCurrDrop.getSelectedItem()));
        return newCurr;
    }
    
    public void currencyValidate() {
        if (oldCurrDrop.getSelectedItem() != "" && newCurrDrop.getSelectedItem() != "") {
            System.out.println(oldCurrDrop.getSelectedItem());
            Double newCurr = 0.0;
            
            try {
                if (oldCurrDrop.getSelectedItem() == newCurrDrop.getSelectedItem()) {
                    newCurr = Double.valueOf(oldCurrAmt.getText());
                }

                else if (Helper.isValidNumber(oldCurrAmt.getText())) {
                    System.out.println("Good to go!");
                    newCurr = convert();   
                }
                else {
                    throw new NumberFormatException("Not a Valid Number");
                }
                newCurrAmt.setText(String.valueOf(String.format("%.2f", newCurr)));
                errLabel.setText("");
            }
            catch (NumberFormatException e) {
                errLabel.setText("Not a valid number");
            }
        }
        else {
            errLabel.setText("Missing values!");
        }
        
        if (errLabel.getText() != "") {
            errLabel.setVisible(true);
            newCurrAmt.setText("");
        }
        else {
            errLabel.setVisible(false);
        }
        // If all 3 are filled, Call convert()
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currency_calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currency_calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currency_calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currency_calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currency_calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errLabel;
    private javax.swing.JLabel newCurrAmt;
    private javax.swing.JComboBox<String> newCurrDrop;
    private javax.swing.JTextField oldCurrAmt;
    private javax.swing.JComboBox<String> oldCurrDrop;
    // End of variables declaration//GEN-END:variables
}
