/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.Image;
import java.util.Dictionary;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author loved
 */

// TODOS:
/*
    Add USD to currencies
    Check values with online version
    Commas and decimals
    Dict of currency symbols
    Option for top 10 most popular currencies
    Fixed horizontal length and line wrapping for text boxes
*/


public class currency_calc extends javax.swing.JFrame {

    /**
     * Creates new form currency_calc
     */
    Map<String, Double> conversionTable = Helper.webScraper();
    Map<String, String> images = new HashMap<>();
    
    public currency_calc() {
        initComponents();
        // Populate images dict
        images.put("Argentine Peso", "Argetina.gif");
        images.put("Australian Dollar", "Australia.gif");
        images.put("Brazilian Real", "Brazil.gif");
        images.put("Canadian Dollar", "Canada.gif");
        images.put("Chilean Pes", "Chile.gif");
        images.put("Hong Kong Dollar", "Hong Kong.gif");
        images.put("Hungarian Forint", "Hungary.gif");
        
        images.put("Mexican Peso", "Mexcio.gif");
        images.put("New Zealand Dollar", "New Zealand.gif");
        images.put("Norwegian Krone", "Norway.gif");
        images.put("Russian Ruble", "Russia.gif");
        images.put("Saudi Arabian Riyal", "Saudi Arabia .gif");
        images.put("\"Singapore Dollar\"", "Singapore.gif");
        images.put("South African Randt", "South Africa gif");
        images.put("Swedish Krona", "Sweden.gif");
        images.put("Swiss Franc", "Switzerland.gif");
        
        
        images.put("US Dollar", "America.gif");
        
        errLabel.setVisible(false);
        
        // Making a dictionary to hold the webscraped currencies and their exchange rates
        // Adding them to the two combo boxes
        //Map<String, Double> conversionTable = Helper.webScraper();
        System.out.println("\n" + conversionTable.get("Euro"));
        DefaultComboBoxModel<String> comboModel1 = new DefaultComboBoxModel <String>();
        DefaultComboBoxModel<String> comboModel2 = new DefaultComboBoxModel <String>();
        for (String key : conversionTable.keySet()){
            comboModel1.addElement(key);
            comboModel2.addElement(key);
        }
        oldCurrDrop.setModel(comboModel1);
        newCurrDrop.setModel(comboModel2);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oldCurrDrop = new javax.swing.JComboBox<>();
        newCurrDrop = new javax.swing.JComboBox<>();
        oldCurrAmt = new javax.swing.JTextField();
        errLabel = new javax.swing.JLabel();
        flip = new javax.swing.JButton();
        newCurrAmt = new javax.swing.JTextField();
        fromFlag = new javax.swing.JLabel();
        toFlag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(550, 375));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oldCurrDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        oldCurrDrop.setName(""); // NOI18N
        oldCurrDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldCurrDropActionPerformed(evt);
            }
        });
        getContentPane().add(oldCurrDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, -1));

        newCurrDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        newCurrDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCurrDropActionPerformed(evt);
            }
        });
        getContentPane().add(newCurrDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 130, -1));

        oldCurrAmt.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        oldCurrAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldCurrAmtActionPerformed(evt);
            }
        });
        getContentPane().add(oldCurrAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 49));

        errLabel.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        errLabel.setForeground(new java.awt.Color(255, 51, 51));
        errLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errLabel.setText("N/A");
        errLabel.setAlignmentX(0.5F);
        getContentPane().add(errLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 180, 140, 40));

        flip.setBackground(new java.awt.Color(0, 102, 255));
        flip.setForeground(new java.awt.Color(255, 255, 255));
        flip.setText("<-->");
        flip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flipMouseClicked(evt);
            }
        });
        getContentPane().add(flip, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        newCurrAmt.setEditable(false);
        newCurrAmt.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(newCurrAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 130, 49));
        getContentPane().add(fromFlag, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 70));
        getContentPane().add(toFlag, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 120, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldCurrDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldCurrDropActionPerformed
        currencyValidate(oldCurrDrop.getSelectedItem(), newCurrDrop.getSelectedItem(), oldCurrAmt.getText());
    }//GEN-LAST:event_oldCurrDropActionPerformed

    private void newCurrDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCurrDropActionPerformed
        currencyValidate(oldCurrDrop.getSelectedItem(), newCurrDrop.getSelectedItem(), oldCurrAmt.getText());
    }//GEN-LAST:event_newCurrDropActionPerformed

    private void oldCurrAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldCurrAmtActionPerformed
        currencyValidate(oldCurrDrop.getSelectedItem(), newCurrDrop.getSelectedItem(), oldCurrAmt.getText());
    }//GEN-LAST:event_oldCurrAmtActionPerformed

    private void flipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flipMouseClicked
        Object oldCurr = oldCurrDrop.getSelectedItem();
        Object newCurr = newCurrDrop.getSelectedItem();
        oldCurrDrop.setSelectedItem(newCurr);
        newCurrDrop.setSelectedItem(oldCurr);
    }//GEN-LAST:event_flipMouseClicked

    /**
     * @param oldCurr
     * @param newCurr
     * @param oldAmt
     * @param args the command line arguments
     * @return 
     */
    
    public Double convert(Object oldCurr, Object newCurr, String oldAmt){
        // oldCurr to USD
        Double newAmt = Double.valueOf(oldAmt) / conversionTable.get(String.valueOf(oldCurr));
        // USD to newCurr
        //System.out.println(String.valueOf(newCurr));
        newAmt *= conversionTable.get(String.valueOf(newCurr));
        return newAmt;
    }
    
    public void currencyValidate(Object oldCurr, Object newCurr, String oldAmt) {
        if (oldCurr != "" && newCurr != "") {
            Double newAmt = 0.0;
            
            try {
                // Converting to same currency
                if (oldCurr == newCurr) {
                    newAmt = Double.valueOf(oldAmt);
                }
                // Converting to different currency with number validation
                else if (Helper.isValidNumber(oldAmt)) {
                    System.out.println("Good to go!");
                    //fromFlag.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("images/" + images.get(String.valueOf(oldCurr)))).getImage().getScaledInstance(120,70, Image.SCALE_SMOOTH)));
                    //toFlag.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("images/" + images.get(String.valueOf(newCurr)))).getImage().getScaledInstance(120,70, Image.SCALE_SMOOTH)));
                    newAmt = convert(oldCurr, newCurr, oldAmt);   
                }
                else {
                    throw new NumberFormatException("Not a Valid Number");
                }
                // Formatting to 5 decimal places like seen on the online calculator
                
                String result = Helper.getSymbol(newCurr, newAmt);
                newCurrAmt.setText(result);
                errLabel.setText("");
            }
            catch (NumberFormatException e) {
                errLabel.setText("Not a valid number");
            }
        }
        else {
            errLabel.setText("Missing values!");
        }
        
        if (errLabel.getText() != "") {
            errLabel.setVisible(true);
            newCurrAmt.setText("");
        }
        else {
            errLabel.setVisible(false);
        }
        // If all 3 are filled, Call convert()
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currency_calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currency_calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currency_calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currency_calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currency_calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errLabel;
    private javax.swing.JButton flip;
    private javax.swing.JLabel fromFlag;
    private javax.swing.JTextField newCurrAmt;
    private javax.swing.JComboBox<String> newCurrDrop;
    private javax.swing.JTextField oldCurrAmt;
    private javax.swing.JComboBox<String> oldCurrDrop;
    private javax.swing.JLabel toFlag;
    // End of variables declaration//GEN-END:variables
}
