/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package groupredproject;

import javax.swing.ImageIcon;
import java.awt.*;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.JButton;
import java.awt.Component;
import java.awt.CardLayout;


/**
 *
 * @author gabby
 */
public class dashboardCapitalCalc extends javax.swing.JFrame {

    /**
     * Creates new form dashboardCapitalCalc
     */
    CardLayout cardLayout;
    public dashboardCapitalCalc() {
        initComponents();
       landingScreenImageLabel.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("Banner (6).png")).getImage()));
       Component [] components = this.getContentPane().getComponents();
        for(Component component : components)
        {
            if(component instanceof JButton jButton)
            {
                jButton.setUI(new BasicButtonUI());
                jButton.setFocusPainted(false);
            }
       }
       cardLayout = (CardLayout)(mainPanel.getLayout());

}

    public void scaleImage(){
        ImageIcon icon = new ImageIcon("MortgageButton.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(mortgageButton.getWidth(), mortgageButton.getHeight(), mortgageButton.getWidth());
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        mortgageButton.setIcon(scaledIcon);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuPanel = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        authorsLabel = new javax.swing.JLabel();
        resourcesLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CapitalCalcLogo = new javax.swing.JLabel();
        logoImage = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        landingScreenPanel = new javax.swing.JPanel();
        subtitleLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        landingScreenImageLabel = new javax.swing.JLabel();
        bottomTitleLabel = new javax.swing.JLabel();
        bottomSubtitleLabel1 = new javax.swing.JLabel();
        bottomeSubtittleLabel2 = new javax.swing.JLabel();
        bottomSubtitleLabel3 = new javax.swing.JLabel();
        currencyLabel = new javax.swing.JLabel();
        retirementLabel = new javax.swing.JLabel();
        mortgageButton = new javax.swing.JLabel();
        loanLabel = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WindowOpen(evt);
            }
        });

        menuPanel.setBackground(new java.awt.Color(62, 142, 224));

        aboutLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setText("About");
        aboutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
        });

        authorsLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        authorsLabel.setForeground(new java.awt.Color(255, 255, 255));
        authorsLabel.setText("Authors");
        authorsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        authorsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                authorsLabelMouseClicked(evt);
            }
        });

        resourcesLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resourcesLabel.setForeground(new java.awt.Color(255, 255, 255));
        resourcesLabel.setText("Resources");
        resourcesLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resourcesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resourcesLabelMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Loan");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Retirement");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Currency");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mortgage");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CapitalCalcLogo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        CapitalCalcLogo.setForeground(new java.awt.Color(255, 255, 255));
        CapitalCalcLogo.setText("CapitalCalc");

        logoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupredproject/CapitalLogo (3).png"))); // NOI18N

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(logoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(aboutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CapitalCalcLogo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resourcesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logoImage)
                .addGap(18, 18, 18)
                .addComponent(CapitalCalcLogo)
                .addGap(29, 29, 29)
                .addComponent(aboutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(authorsLabel)
                .addGap(18, 18, 18)
                .addComponent(resourcesLabel)
                .addGap(92, 92, 92)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addComponent(jLabel8)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(menuPanel);
        menuPanel.getAccessibleContext().setAccessibleName("menuPanel");

        mainPanel.setBackground(new java.awt.Color(153, 204, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        landingScreenPanel.setBackground(new java.awt.Color(255, 255, 255));

        subtitleLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitleLabel.setText("Use our financial calculators to guide \nyou on your way to a comfy future");

        titleLabel.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        titleLabel.setText("Financial Calculators");

        landingScreenImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banner (6).png"))); // NOI18N
        landingScreenImageLabel.setText(".");

        bottomTitleLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        bottomTitleLabel.setText("Crunch the numbers");

        bottomSubtitleLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bottomSubtitleLabel1.setText("Select from the varying calculators from retirement, mortgage, currency, or loans and calculate ");

        bottomeSubtittleLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bottomeSubtittleLabel2.setText("your future. We include the real life variables like interest rates, debts, and income to allow ");

        bottomSubtitleLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bottomSubtitleLabel3.setText("you to weigh your financial decisions and create a comfortable future ");

        currencyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupredproject/currencyicon (1).png"))); // NOI18N
        currencyLabel.setText("jLabel17");
        currencyLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        currencyLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        retirementLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupredproject/Retirementicon (1).png"))); // NOI18N
        retirementLabel.setText("jLabel17");
        retirementLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        retirementLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mortgageButton.setBackground(new java.awt.Color(62, 142, 224));
        mortgageButton.setForeground(new java.awt.Color(62, 142, 224));
        mortgageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupredproject/mortgageButtonIcon.png"))); // NOI18N
        mortgageButton.setText(" ");
        mortgageButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        mortgageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        loanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupredproject/loanButtonIcon.png"))); // NOI18N
        loanLabel.setText("jLabel17");
        loanLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        loanLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loanLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loanLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout landingScreenPanelLayout = new javax.swing.GroupLayout(landingScreenPanel);
        landingScreenPanel.setLayout(landingScreenPanelLayout);
        landingScreenPanelLayout.setHorizontalGroup(
            landingScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landingScreenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(landingScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bottomTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottomSubtitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landingScreenImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(landingScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bottomSubtitleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bottomeSubtittleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(landingScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingScreenPanelLayout.createSequentialGroup()
                        .addComponent(loanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(landingScreenPanelLayout.createSequentialGroup()
                        .addGroup(landingScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(retirementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(landingScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mortgageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(currencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(landingScreenPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(landingScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        landingScreenPanelLayout.setVerticalGroup(
            landingScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landingScreenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(landingScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(landingScreenPanelLayout.createSequentialGroup()
                        .addComponent(loanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(retirementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(currencyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mortgageButton))
                    .addGroup(landingScreenPanelLayout.createSequentialGroup()
                        .addComponent(subtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landingScreenImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bottomTitleLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomSubtitleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomeSubtittleLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottomSubtitleLabel3)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        mainPanel.add(landingScreenPanel, "card2");

        aboutPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("jLabel2");
        aboutPanel.add(jLabel2, "card2");

        mainPanel.add(aboutPanel, "card3");

        jSplitPane1.setRightComponent(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WindowOpen(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowOpen
        // Landing Screen Opened- Text Animation
        //Boundary
        final int MAX_X = 450;
        final int MIN_X = 50;
        
        Thread animation = new Thread(new Runnable(){
            @Override
            public void run() {
               int x = 20;
               int y = 30; // label start position
               while(true) {
                   titleLabel.setLocation(x, y);
                   x +=10;
                   
                   try{
                       Thread.sleep(200);
                   } catch (Exception e) {
                       
                   }
               }
               
            }
            
        });
        //animation.start();
        
    }//GEN-LAST:event_WindowOpen

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        // About Frame
        
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void authorsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorsLabelMouseClicked
        // Authors Panel
        
    }//GEN-LAST:event_authorsLabelMouseClicked

    private void resourcesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resourcesLabelMouseClicked
        // Resources Frame
        //cardLayout.show(mainPanel, "aboutPanel");
    }//GEN-LAST:event_resourcesLabelMouseClicked

    private void loanLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanLabelMousePressed
        // Loan Calculators
        //cardLayout.show(mainPanel, "aboutPanel");
    }//GEN-LAST:event_loanLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardCapitalCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardCapitalCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardCapitalCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardCapitalCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardCapitalCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CapitalCalcLogo;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JLabel bottomSubtitleLabel1;
    private javax.swing.JLabel bottomSubtitleLabel3;
    private javax.swing.JLabel bottomTitleLabel;
    private javax.swing.JLabel bottomeSubtittleLabel2;
    private javax.swing.JLabel currencyLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel landingScreenImageLabel;
    private javax.swing.JPanel landingScreenPanel;
    private javax.swing.JLabel loanLabel;
    private javax.swing.JLabel logoImage;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel mortgageButton;
    private javax.swing.JLabel resourcesLabel;
    private javax.swing.JLabel retirementLabel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
