
import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author loved
 */
public class mortgageCalc extends javax.swing.JFrame {

    /**
     * Creates new form mortCalc
     */
    DecimalFormat df = new DecimalFormat("#.##");
    public mortgageCalc() {
        initComponents();
        panel2.setVisible(false);
        panel3.setVisible(false);
        prct4.setVisible(false);
        prct6.setVisible(false);
        prct7.setVisible(false);
        prct8.setVisible(false);
        prct9.setVisible(false);
        prct10.setVisible(false);
    }
/*
   class Slice {
   double value;
   Color color;
   public Slice(double value, Color color) {  
      this.value = value;
      this.color = color;
   }
}
class PieChart3 extends JComponent {
   Slice[] slices = { new Slice(5, Color.black), 
   new Slice(33, Color.green),
   new Slice(20, Color.yellow), new Slice(15, Color.red) };
   PieChart3() {}
   public void paint(Graphics g) {
      drawPie((Graphics2D) g, getBounds(), slices);
   }
   void drawPie(Graphics2D g, Rectangle area, Slice[] slices) {
      double total = 0.0D;
      for (int i = 0; i < slices.length; i++) {
         total += slices[i].value;
      }
      double curValue = 0.0D;
      int startAngle = 0;
      for (int i = 0; i < slices.length; i++) {
         startAngle = (int) (curValue * 360 / total);
         int arcAngle = (int) (slices[i].value * 360 / total);
         g.setColor(slices[i].color);
         g.fillArc(area.x, area.y, area.width, area.height, 
         startAngle, arcAngle);
         curValue += slices[i].value;
      }
   }
    */
    public Double monthlyMortgage(Double p, Double r, Double n) {
        r /= 1200;
        n *= 12;
        System.out.println(p + "   " + n + "   " + r*Math.pow((1+r), n)/(Math.pow(1+r, n) -1));
        Double m = p*(r*Math.pow(1+r, n)/(Math.pow(1+r, n) -1));
        System.out.println("Monthly Payment is $" + m);
        return m;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        downPayLabel = new javax.swing.JLabel();
        interestLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        downPayAmt = new javax.swing.JTextField();
        interestAmt = new javax.swing.JTextField();
        loanTermAmt = new javax.swing.JTextField();
        homePriceAmt = new javax.swing.JTextField();
        homePriceLabel = new javax.swing.JLabel();
        loanTermLabel = new javax.swing.JLabel();
        dr1 = new javax.swing.JLabel();
        dr2 = new javax.swing.JLabel();
        loanTermYr = new javax.swing.JLabel();
        dr4 = new javax.swing.JLabel();
        prct4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        yr = new javax.swing.JTextField();
        month = new javax.swing.JComboBox<>();
        comboBox4 = new javax.swing.JComboBox<>();
        panel2 = new javax.swing.JPanel();
        homeInsuranceLabel = new javax.swing.JLabel();
        hoaLabel = new javax.swing.JLabel();
        otherLabel = new javax.swing.JLabel();
        homeInsuranceAmt = new javax.swing.JTextField();
        hoaAmt = new javax.swing.JTextField();
        otherAmt = new javax.swing.JTextField();
        pmiAmt = new javax.swing.JTextField();
        propTaxAmt = new javax.swing.JTextField();
        propTaxLabel = new javax.swing.JLabel();
        pmiInsuranceLabel = new javax.swing.JLabel();
        dr6 = new javax.swing.JLabel();
        dr7 = new javax.swing.JLabel();
        dr9 = new javax.swing.JLabel();
        prct9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        prct6 = new javax.swing.JLabel();
        dr8 = new javax.swing.JLabel();
        dr10 = new javax.swing.JLabel();
        prct7 = new javax.swing.JLabel();
        prct8 = new javax.swing.JLabel();
        prct10 = new javax.swing.JLabel();
        comboBox6 = new javax.swing.JComboBox<>();
        comboBox7 = new javax.swing.JComboBox<>();
        comboBox8 = new javax.swing.JComboBox<>();
        comboBox9 = new javax.swing.JComboBox<>();
        comboBox10 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        calc = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        monthlyPay = new javax.swing.JTextField();
        housePayLabel = new javax.swing.JLabel();
        downPayLabel2 = new javax.swing.JLabel();
        housePayAmt = new javax.swing.JLabel();
        totalInterestLabel = new javax.swing.JLabel();
        totalAmtLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        totalInterest = new javax.swing.JLabel();
        downPayAmt2 = new javax.swing.JLabel();
        totalAmt = new javax.swing.JLabel();
        endDate = new javax.swing.JLabel();
        monthPayLabel = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        XBtn = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        infoPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1650, 1800));
        setSize(new java.awt.Dimension(1650, 1800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CapitalLogo.png"))); // NOI18N
        logo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 471, -1));

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(66, 133, 244));
        title.setText("Mortgage Calculator");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        panel1.setBackground(new java.awt.Color(245, 245, 245));

        downPayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        downPayLabel.setText("Down Payment");
        downPayLabel.setPreferredSize(new java.awt.Dimension(128, 17));
        downPayLabel.setRequestFocusEnabled(false);

        interestLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        interestLabel.setText("Interest Rate");

        startDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        startDateLabel.setText("Start Date");

        downPayAmt.setBackground(new java.awt.Color(199, 219, 252));
        downPayAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        downPayAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                downPayAmtKeyTyped(evt);
            }
        });

        interestAmt.setBackground(new java.awt.Color(163, 195, 248));
        interestAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        interestAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                interestAmtKeyTyped(evt);
            }
        });

        loanTermAmt.setBackground(new java.awt.Color(199, 219, 252));
        loanTermAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loanTermAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loanTermAmtKeyTyped(evt);
            }
        });

        homePriceAmt.setBackground(new java.awt.Color(163, 195, 248));
        homePriceAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homePriceAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homePriceAmtKeyTyped(evt);
            }
        });

        homePriceLabel.setBackground(new java.awt.Color(0, 0, 0));
        homePriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homePriceLabel.setText("Home Price");
        homePriceLabel.setFocusCycleRoot(true);

        loanTermLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loanTermLabel.setText("Loan Term");

        dr1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dr1.setText("$");

        dr2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dr2.setText("$");

        loanTermYr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loanTermYr.setText("years");

        dr4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dr4.setText("$");

        prct4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prct4.setText("%");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setPreferredSize(new java.awt.Dimension(42, 17));

        yr.setBackground(new java.awt.Color(199, 219, 252));
        yr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yrKeyTyped(evt);
            }
        });

        month.setBackground(new java.awt.Color(199, 219, 252));
        month.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        comboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "$", "%" }));
        comboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homePriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downPayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loanTermLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(interestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(comboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yr, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addComponent(dr1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(homePriceAmt))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dr2)
                                .addComponent(dr4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(interestAmt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(downPayAmt)
                                .addComponent(loanTermAmt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loanTermYr)
                    .addComponent(prct4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homePriceAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dr1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downPayAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dr2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loanTermAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loanTermYr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(interestAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dr4)
                            .addComponent(prct4)
                            .addComponent(comboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(homePriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downPayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(loanTermLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(interestLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startDateLabel)
                                .addGap(60, 60, 60))))))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 222, 470, 160));

        panel2.setBackground(new java.awt.Color(245, 245, 245));

        homeInsuranceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeInsuranceLabel.setText("Home Insurance");
        homeInsuranceLabel.setPreferredSize(new java.awt.Dimension(128, 17));
        homeInsuranceLabel.setRequestFocusEnabled(false);

        hoaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hoaLabel.setText("HOA Fee");

        otherLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        otherLabel.setText("Other Fees");

        homeInsuranceAmt.setBackground(new java.awt.Color(199, 219, 252));
        homeInsuranceAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homeInsuranceAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homeInsuranceAmtKeyTyped(evt);
            }
        });

        hoaAmt.setBackground(new java.awt.Color(163, 195, 248));
        hoaAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hoaAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hoaAmtKeyTyped(evt);
            }
        });

        otherAmt.setBackground(new java.awt.Color(199, 219, 252));
        otherAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        otherAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otherAmtKeyTyped(evt);
            }
        });

        pmiAmt.setBackground(new java.awt.Color(199, 219, 252));
        pmiAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pmiAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pmiAmtKeyTyped(evt);
            }
        });

        propTaxAmt.setBackground(new java.awt.Color(163, 195, 248));
        propTaxAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        propTaxAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                propTaxAmtKeyTyped(evt);
            }
        });

        propTaxLabel.setBackground(new java.awt.Color(0, 0, 0));
        propTaxLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        propTaxLabel.setText("Property Taxes");
        propTaxLabel.setFocusCycleRoot(true);

        pmiInsuranceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pmiInsuranceLabel.setText("PMI Insurance");

        dr6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dr6.setText("$");

        dr7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dr7.setText("$");

        dr9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dr9.setText("$");

        prct9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prct9.setText("%");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setPreferredSize(new java.awt.Dimension(42, 17));

        prct6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prct6.setText("%");

        dr8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dr8.setText("$");

        dr10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dr10.setText("$");

        prct7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prct7.setText("%");

        prct8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prct8.setText("%");

        prct10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prct10.setText("%");

        comboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "$", "%" }));
        comboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox6ActionPerformed(evt);
            }
        });

        comboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "$", "%" }));
        comboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox7ActionPerformed(evt);
            }
        });

        comboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "$", "%" }));
        comboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox8ActionPerformed(evt);
            }
        });

        comboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "$", "%" }));
        comboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox9ActionPerformed(evt);
            }
        });

        comboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "$", "%" }));
        comboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propTaxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeInsuranceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pmiInsuranceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hoaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(otherLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBox6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox8, 0, 1, Short.MAX_VALUE)
                    .addComponent(comboBox9, 0, 1, Short.MAX_VALUE)
                    .addComponent(comboBox10, 0, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(dr10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherAmt))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(dr7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeInsuranceAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(dr6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propTaxAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(dr8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pmiAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(dr9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hoaAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(prct9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prct6)
                    .addComponent(prct7)
                    .addComponent(prct8)
                    .addComponent(prct10))
                .addGap(7, 7, 7))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propTaxAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propTaxLabel)
                    .addComponent(dr6)
                    .addComponent(prct6)
                    .addComponent(comboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeInsuranceAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeInsuranceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dr7)
                    .addComponent(prct7)
                    .addComponent(comboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pmiAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pmiInsuranceLabel)
                            .addComponent(dr8)
                            .addComponent(prct8)
                            .addComponent(comboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoaAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hoaLabel)
                            .addComponent(dr9)
                            .addComponent(prct9)
                            .addComponent(comboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(otherLabel)
                        .addComponent(dr10)
                        .addComponent(comboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(otherAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prct10)))
                .addGap(57, 57, 57))
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 460, 160));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jCheckBox1.setText("Include Taxes & Costs");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        calc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        calc.setText("Calculate");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        getContentPane().add(calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 168, -1));

        panel3.setBackground(new java.awt.Color(245, 245, 245));

        monthlyPay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        housePayLabel.setBackground(new java.awt.Color(0, 0, 0));
        housePayLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        housePayLabel.setText("House Payment");
        housePayLabel.setFocusCycleRoot(true);

        downPayLabel2.setBackground(new java.awt.Color(0, 0, 0));
        downPayLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        downPayLabel2.setText("Down Payment");
        downPayLabel2.setFocusCycleRoot(true);

        housePayAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        housePayAmt.setText("0.00");

        totalInterestLabel.setBackground(new java.awt.Color(0, 0, 0));
        totalInterestLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalInterestLabel.setText("Total Interest");
        totalInterestLabel.setFocusCycleRoot(true);

        totalAmtLabel.setBackground(new java.awt.Color(0, 0, 0));
        totalAmtLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalAmtLabel.setText("Total Amount");
        totalAmtLabel.setFocusCycleRoot(true);

        endDateLabel.setBackground(new java.awt.Color(0, 0, 0));
        endDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        endDateLabel.setText("Mortgage Payoff Date");
        endDateLabel.setFocusCycleRoot(true);

        totalInterest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalInterest.setText("0.00");

        downPayAmt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        downPayAmt2.setText("0.00");

        totalAmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalAmt.setText("0.00");

        endDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        endDate.setText("0.00");

        monthPayLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthPayLabel.setText("Monthly Payment");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthPayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downPayLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalInterestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(housePayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalAmtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthlyPay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downPayAmt2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(housePayAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthPayLabel)
                    .addComponent(monthlyPay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housePayLabel)
                    .addComponent(housePayAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downPayLabel2)
                    .addComponent(downPayAmt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalInterestLabel)
                    .addComponent(totalInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAmtLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateLabel)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 230, -1, -1));

        clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 99, -1));

        jPanel1.setBackground(new java.awt.Color(66, 133, 244));

        XBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        XBtn.setForeground(new java.awt.Color(255, 51, 51));
        XBtn.setText("X");
        XBtn.setBorderPainted(false);
        XBtn.setFocusPainted(false);
        XBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1621, Short.MAX_VALUE)
                .addComponent(XBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(XBtn)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, -1));

        infoLabel.setBackground(new java.awt.Color(199, 219, 252));
        infoLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(66, 133, 244));
        infoLabel.setText(" ? ");
        infoLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 133, 244), 4, true));
        infoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoLabelMouseExited(evt);
            }
        });
        getContentPane().add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, -1, -1));

        infoPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mortgageInfo.png"))); // NOI18N
        infoPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 244)));
        getContentPane().add(infoPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, 278, 104));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        panel2.setVisible(!panel2.isVisible());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        if (!homePriceAmt.getText().isEmpty() && !downPayAmt.getText().isEmpty() && !loanTermAmt.getText().isEmpty() && !interestAmt.getText().isEmpty() && month.getSelectedItem() != "" && !yr.getText().isEmpty()) {
            panel3.setVisible(true);
            
            try {
                Double p = Double.valueOf(homePriceAmt.getText()) - Double.valueOf(downPayAmt.getText());
                
                Double m = monthlyMortgage(p, Double.valueOf(interestAmt.getText()), Double.valueOf(loanTermAmt.getText()));
                monthlyPay.setText("$" + df.format(m));
                
                housePayAmt.setText("$" + homePriceAmt.getText());
                downPayAmt2.setText("$" + downPayAmt.getText());
                Double total = Double.valueOf(monthlyPay.getText().replace("$", ""))*12*Double.valueOf(loanTermAmt.getText());
                totalAmt.setText("$" + df.format(total));
                totalInterest.setText("$" + df.format(total-p));
                
                int y = (int) Math.round(total/m);
                int expMonths = (int) Math.ceil(y)%12;
                int expYrs = (int) y/12;
                int endYr = Integer.parseInt(yr.getText()) + expYrs;
                int startMonth = Helper.intFromMonth(month.getSelectedItem().toString());
                String endMonth = Helper.monthFromInt(String.valueOf((startMonth+expMonths)%12));
                endDate.setText(endMonth + " " + endYr);
            }
            catch (NumberFormatException e) {
                System.out.println("Not a valid number");
                // Make a pop-up error
                //errLabel.setText("Not a valid number");
            }
        }
    }//GEN-LAST:event_calcActionPerformed

    private void homePriceAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homePriceAmtKeyTyped
        Helper.validateInput(homePriceAmt, evt);
    }//GEN-LAST:event_homePriceAmtKeyTyped

    private void downPayAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_downPayAmtKeyTyped
        Helper.validateInput(downPayAmt, evt);
    }//GEN-LAST:event_downPayAmtKeyTyped

    private void loanTermAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanTermAmtKeyTyped
        Helper.validateInput(loanTermAmt, evt);
    }//GEN-LAST:event_loanTermAmtKeyTyped

    private void interestAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_interestAmtKeyTyped
        Helper.validateInput(interestAmt, evt);
    }//GEN-LAST:event_interestAmtKeyTyped

    private void yrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yrKeyTyped
        Helper.validateInput(yr, evt);
    }//GEN-LAST:event_yrKeyTyped

    private void homeInsuranceAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeInsuranceAmtKeyTyped
        Helper.validateInput(homeInsuranceAmt, evt);
    }//GEN-LAST:event_homeInsuranceAmtKeyTyped

    private void pmiAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pmiAmtKeyTyped
        Helper.validateInput(pmiAmt, evt);
    }//GEN-LAST:event_pmiAmtKeyTyped

    private void hoaAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hoaAmtKeyTyped
        Helper.validateInput(pmiAmt, evt);
    }//GEN-LAST:event_hoaAmtKeyTyped

    private void otherAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherAmtKeyTyped
        Helper.validateInput(otherAmt, evt);
    }//GEN-LAST:event_otherAmtKeyTyped

    private void propTaxAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_propTaxAmtKeyTyped
        Helper.validateInput(propTaxAmt, evt);
    }//GEN-LAST:event_propTaxAmtKeyTyped

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        homePriceAmt.setText("");
        downPayAmt.setText("");
        loanTermAmt.setText("");
        interestAmt.setText("");
        month.setSelectedItem("Jan");
        yr.setText("");
        propTaxAmt.setText("");
        homeInsuranceAmt.setText("");
        pmiAmt.setText("");
        hoaAmt.setText("");
        otherAmt.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void XBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_XBtnMouseClicked

    private void comboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox4ActionPerformed
        if (comboBox4.getSelectedItem() == "$") {
            dr4.setVisible(true);
            prct4.setVisible(false);
        }
        else {
            dr4.setVisible(false);
            prct4.setVisible(true);
        }
    }//GEN-LAST:event_comboBox4ActionPerformed

    private void comboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox6ActionPerformed
        if (comboBox6.getSelectedItem() == "$") {
            dr6.setVisible(true);
            prct6.setVisible(false);
        }
        else {
            dr6.setVisible(false);
            prct6.setVisible(true);
        }
    }//GEN-LAST:event_comboBox6ActionPerformed

    private void comboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox7ActionPerformed
        if (comboBox7.getSelectedItem() == "$") {
            dr7.setVisible(true);
            prct7.setVisible(false);
        }
        else {
            dr7.setVisible(false);
            prct7.setVisible(true);
        }
    }//GEN-LAST:event_comboBox7ActionPerformed

    private void comboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox8ActionPerformed
        if (comboBox8.getSelectedItem() == "$") {
            dr8.setVisible(true);
            prct8.setVisible(false);
        }
        else {
            dr8.setVisible(false);
            prct8.setVisible(true);
        }
    }//GEN-LAST:event_comboBox8ActionPerformed

    private void comboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox9ActionPerformed
        if (comboBox9.getSelectedItem() == "$") {
            dr9.setVisible(true);
            prct9.setVisible(false);
        }
        else {
            dr9.setVisible(false);
            prct9.setVisible(true);
        }
    }//GEN-LAST:event_comboBox9ActionPerformed

    private void comboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox10ActionPerformed
        if (comboBox10.getSelectedItem() == "$") {
            dr10.setVisible(true);
            prct10.setVisible(false);
        }
        else {
            dr10.setVisible(false);
            prct10.setVisible(true);
        }
    }//GEN-LAST:event_comboBox10ActionPerformed

    private void infoLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoLabelMouseEntered
        infoPic.setVisible(true);
    }//GEN-LAST:event_infoLabelMouseEntered

    private void infoLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoLabelMouseExited
        infoPic.setVisible(false);
    }//GEN-LAST:event_infoLabelMouseExited

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        calcPage2_mortgage calc2 = new calcPage2_mortgage();
        calc2.setSize(1650, 1800);
        calc2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mortgageCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mortgageCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mortgageCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mortgageCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mortgageCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XBtn;
    private javax.swing.JButton calc;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> comboBox10;
    private javax.swing.JComboBox<String> comboBox4;
    private javax.swing.JComboBox<String> comboBox6;
    private javax.swing.JComboBox<String> comboBox7;
    private javax.swing.JComboBox<String> comboBox8;
    private javax.swing.JComboBox<String> comboBox9;
    private javax.swing.JTextField downPayAmt;
    private javax.swing.JLabel downPayAmt2;
    private javax.swing.JLabel downPayLabel;
    private javax.swing.JLabel downPayLabel2;
    private javax.swing.JLabel dr1;
    private javax.swing.JLabel dr10;
    private javax.swing.JLabel dr2;
    private javax.swing.JLabel dr4;
    private javax.swing.JLabel dr6;
    private javax.swing.JLabel dr7;
    private javax.swing.JLabel dr8;
    private javax.swing.JLabel dr9;
    private javax.swing.JLabel endDate;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField hoaAmt;
    private javax.swing.JLabel hoaLabel;
    private javax.swing.JTextField homeInsuranceAmt;
    private javax.swing.JLabel homeInsuranceLabel;
    private javax.swing.JTextField homePriceAmt;
    private javax.swing.JLabel homePriceLabel;
    private javax.swing.JLabel housePayAmt;
    private javax.swing.JLabel housePayLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel infoPic;
    private javax.swing.JTextField interestAmt;
    private javax.swing.JLabel interestLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loanTermAmt;
    private javax.swing.JLabel loanTermLabel;
    private javax.swing.JLabel loanTermYr;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JLabel monthPayLabel;
    private javax.swing.JTextField monthlyPay;
    private javax.swing.JTextField otherAmt;
    private javax.swing.JLabel otherLabel;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JTextField pmiAmt;
    private javax.swing.JLabel pmiInsuranceLabel;
    private javax.swing.JLabel prct10;
    private javax.swing.JLabel prct4;
    private javax.swing.JLabel prct6;
    private javax.swing.JLabel prct7;
    private javax.swing.JLabel prct8;
    private javax.swing.JLabel prct9;
    private javax.swing.JTextField propTaxAmt;
    private javax.swing.JLabel propTaxLabel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalAmt;
    private javax.swing.JLabel totalAmtLabel;
    private javax.swing.JLabel totalInterest;
    private javax.swing.JLabel totalInterestLabel;
    private javax.swing.JTextField yr;
    // End of variables declaration//GEN-END:variables
}
