import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.Arrays;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author litchar
 */
public class refinanceCalc extends javax.swing.JFrame {

    /**
     * Creates new form refinanceCalc
     */;
    public refinanceCalc() {
        initComponents();
        jLabel14.setOpaque(true);
        jLabel14.setBackground(Color.decode("#c7dbfc"));
        jLabel3.setOpaque(true);
        jLabel3.setBackground(Color.decode("#c7dbfc"));   
        jLabel7.setOpaque(true);
        jLabel7.setBackground(Color.decode("#c7dbfc"));   
           
        jLabel13.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel25.setVisible(false);
        jLabel27.setVisible(false);
        jLabel29.setVisible(false);
        
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
                
        this.getContentPane().setBackground(Color.white);
        //this.getContentPane().setBackground(Color.decode("#c7dbfc"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 133, 244));
        jLabel1.setText("Refinance Calculator");

        jLabel2.setBackground(new java.awt.Color(199, 219, 252));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 133, 244));
        jLabel2.setText(" ?");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 133, 244), 4, true));
        jLabel2.setPreferredSize(new java.awt.Dimension(23, 25));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CapitalLogo.png"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 244)));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refinanceInfo.png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 244)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("                         New Loan");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 244)));
        jLabel7.setPreferredSize(new java.awt.Dimension(183, 18));

        jLabel8.setText("New Loan Term");

        jLabel9.setText("Interest Rate");

        jLabel10.setText("Cost and Fees");

        jLabel11.setBackground(new java.awt.Color(199, 219, 252));
        jLabel11.setText("Cash-Out Amount");

        jTextField4.setBackground(new java.awt.Color(163, 195, 248));

        jTextField5.setBackground(new java.awt.Color(199, 219, 252));

        jTextField6.setBackground(new java.awt.Color(163, 195, 248));

        jTextField7.setBackground(new java.awt.Color(199, 219, 252));

        jTextField9.setBackground(new java.awt.Color(163, 195, 248));

        jLabel15.setText("Points");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel3.setBackground(new java.awt.Color(199, 219, 252));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                           Current Loan");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 244)));

        jLabel4.setText("Remaining Balance   ");
        jLabel4.setPreferredSize(new java.awt.Dimension(128, 17));
        jLabel4.setRequestFocusEnabled(false);

        jLabel5.setText("Monthly Payment");

        jLabel6.setText("Interest Rate");

        jTextField1.setBackground(new java.awt.Color(199, 219, 252));

        jTextField2.setBackground(new java.awt.Color(163, 195, 248));

        jTextField3.setBackground(new java.awt.Color(199, 219, 252));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I know my Remaining Balance", "I know the Original Loan Amount" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField11.setBackground(new java.awt.Color(199, 219, 252));

        jTextField12.setBackground(new java.awt.Color(163, 195, 248));

        jTextField13.setBackground(new java.awt.Color(199, 219, 252));

        jTextField14.setBackground(new java.awt.Color(163, 195, 248));
        jTextField14.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextField14ComponentAdded(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Original Loan Amount");
        jLabel19.setFocusCycleRoot(true);

        jLabel20.setText("Loan Term");

        jLabel21.setText("Time Remaining");

        jLabel22.setText("Interest Rate");

        jLabel23.setText("$");

        jLabel24.setText("$");

        jLabel25.setText("years");

        jLabel26.setText("$");

        jLabel27.setText("years");

        jLabel28.setText("%");

        jLabel29.setText("%");

        jLabel30.setPreferredSize(new java.awt.Dimension(42, 17));
        jLabel30.setSize(new java.awt.Dimension(42, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel28)
                                .addComponent(jLabel29)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel26)))
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel29))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(199, 219, 252));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calculate");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(183, 183, 183));
        jButton2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton2.setText("Clear");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(271, 271, 271))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(199, 219, 252));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 133, 244), 1, true));

        jTextField10.setEditable(false);

        jLabel16.setText("Refinancing would be...");

        jTextPane1.setEditable(false);
        jScrollPane2.setViewportView(jTextPane1);

        jLabel17.setText("New Monthly Payment:");

        jTextField8.setEditable(false);

        jLabel18.setText("$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField10)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(5, 5, 5)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel14.setBackground(new java.awt.Color(199, 219, 252));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("   Results");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jButton3.setText("X");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3))
            .addGroup(layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBox1.getSelectedItem();
        if (selectedItem == "I know the Original Loan Amount") {
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel24.setVisible(false);
            jLabel26.setVisible(false);
            jLabel28.setVisible(false);
            
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(false);
            
            jLabel19.setVisible(true);
            jLabel20.setVisible(true);
            jLabel21.setVisible(true);
            jLabel22.setVisible(true);
            jLabel23.setVisible(true);
            jLabel25.setVisible(true);
            jLabel27.setVisible(true);
            jLabel29.setVisible(true);
        
            jTextField11.setVisible(true);
            jTextField12.setVisible(true);
            jTextField13.setVisible(true);
            jTextField14.setVisible(true);
        } else {
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel24.setVisible(true);
            jLabel26.setVisible(true);
            jLabel28.setVisible(true);
            
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            
            jLabel19.setVisible(false);
            jLabel20.setVisible(false);
            jLabel21.setVisible(false);
            jLabel22.setVisible(false);
            jLabel23.setVisible(false);
            jLabel25.setVisible(false);
            jLabel27.setVisible(false);
            jLabel29.setVisible(false);
        
            jTextField11.setVisible(false);
            jTextField12.setVisible(false);
            jTextField13.setVisible(false);
            jTextField14.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String selectedItem = (String) jComboBox1.getSelectedItem();
        if (selectedItem == "I know my Remaining Balance") {
        
        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Remaining Balance.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField1.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Remaining Balance must be numeric. Try again!");
        } else if (Double.parseDouble(jTextField1.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Remaining Balance must be positive. Try again!");
        } else if (jTextField2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Monthly Payment.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField2.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Monthly Payment must be numeric. Try again!");
        } else if (Double.parseDouble(jTextField2.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Remaining Balance must be greater than 0. Try again!");
        } else if (jTextField3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Current Loan's Interest Rate.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField3.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Interest Rate must be numeric. Try again!");
        } else if (Double.parseDouble(jTextField3.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Interest Rate must be positive. Try again!");
        } else if (jTextField4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for New Loan Term.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField4.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: New Loan Term must be numeric. Try again!");
        } else if (Double.parseDouble(jTextField4.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: New Loan Term must be greater than 0. Try again!");
        } else if (Double.parseDouble(jTextField4.getText()) > 1000) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: New Loan Term must be less than 1000. Try again!");       
        } else if (jTextField5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for New Loan's Interest Rate.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField5.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: New Loan's Interest Rate must be numeric. Try again!");
        } else if (Double.parseDouble(jTextField5.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: New Loan's Interest Rate must be positive. Try again!");
        } else if (Double.parseDouble(jTextField5.getText()) > 100) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: New Loan's Interest Rate must be less than 100. Try again!");       
        } else if (jTextField6.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Points.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField6.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Points must be numeric. Try again!");
        } else if (Double.parseDouble(jTextField6.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Points must be positive. Try again!");
        } else if (Double.parseDouble(jTextField6.getText()) > 100) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Points must be less than 100. Try again!");       
        } else if (jTextField7.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Costs and Fees.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField7.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Cost and Fees must be numeric. Try again!");
        } else if (Double.parseDouble(jTextField7.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Cost and Fees must be positive. Try again!");
        } else if (jTextField9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Cash-Out Amount.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField9.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Cash-Out Amount must be numeric. Try again!");
        
        } else {
        // CURRENT Loan:
        double remainingBalance = Double.parseDouble(jTextField1.getText());
        double monthlyPayment = Double.parseDouble(jTextField2.getText());
        double oldInterestRate = Double.parseDouble(jTextField3.getText())/100;
        
        // NEW Loan:
        double newLoanTerm = Double.parseDouble(jTextField4.getText());
        double newInterestRate = Double.parseDouble(jTextField5.getText())/100;
        double points = Double.parseDouble(jTextField6.getText());
        double costs = Double.parseDouble(jTextField7.getText());
        double cashOut = Double.parseDouble(jTextField9.getText());
        
        double monthlyAmt = interestHelper.refinanceCalc((remainingBalance + cashOut), newLoanTerm, newInterestRate);
        System.out.print("Amount Paid (w/ interest) :" + (monthlyAmt * 12 * newLoanTerm));       
        
        double diff = 100 * Math.abs(oldInterestRate - newInterestRate);
        if (oldInterestRate < newInterestRate) {
            List<String> output = Arrays.asList("The APR for the new loan is", String.format("%.2f", newInterestRate), "- this is", String.valueOf(String.format("%.2f", diff) + "%"), "higher than the", String.format("%.2f", oldInterestRate), "interest rate of the current loan.");
            String joinedString = String.join(" ", output);
            jTextPane1.setText(joinedString);
            jTextField10.setText("financially MORE expensive.");
            jTextField8.setText(String.format("%.2f", monthlyAmt));
            
        } else if (oldInterestRate > newInterestRate) {
            List<String> output = Arrays.asList("The APR for the new loan is", String.format("%.2f", newInterestRate), "- this is", String.valueOf(String.format("%.2f", diff) + "%"), "lower than the", String.format("%.2f", oldInterestRate), "interest rate of the current loan.");
            String joinedString = String.join(" ", output);
            jTextPane1.setText(joinedString);
            jTextField10.setText("financially LESS expensive.");
            jTextField8.setText(String.format("%.2f", monthlyAmt));
        } else {
            List<String> output = Arrays.asList("The APR for the new loan is", String.format("%.2f", newInterestRate), "- this is equal to the", String.format("%.2f", oldInterestRate), "interest rate of the current loan.");
            String joinedString = String.join(" ", output);
            jTextPane1.setText(joinedString);
            jTextField10.setText("comparable in cost to the existing loan!");
            jTextField8.setText(String.format("%.2f", monthlyAmt));
        }
        }
        
        } else {
        if (jTextField14.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Original Loan Amount.");
        } else if (Helper.isPos(String.valueOf(Double.parseDouble(jTextField14.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Original Loan Amount must be a number greater than 0. Try again!");
        } else if (jTextField11.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Loan Term.");
        } else if (Helper.isPos(String.valueOf(Double.parseDouble(jTextField11.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Loan Term must be a positive number. Try again!");
        } else if (jTextField12.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Time Remaining.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField12.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Time Remaining must be numeric. Try again!");
        } else if (Double.parseDouble(jTextField12.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Time Remaining must be positive. Try again!");
        } else if (Double.parseDouble(jTextField11.getText()) < (Double.parseDouble(jTextField12.getText()))) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Time Remaining must be less than or equal to Loan Term. Try again!");
        } else if (jTextField13.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a value for Interest Rate.");
        } else if (Helper.isValidNumber(String.valueOf(Double.parseDouble(jTextField13.getText()))) == false) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Interest Rate must be numeric. Try again!");
        } else if ( (Double.parseDouble(jTextField13.getText()) < 0) || (Double.parseDouble(jTextField13.getText()) > 200) ) {
            JOptionPane.showMessageDialog(null, "INPUT INVALID: Interest Rate must be between 0 and 200. Try again!");
        } else {
            // CURRENT Loan
        double originalLoan = Double.parseDouble(jTextField14.getText());
        double loanTerm = Double.parseDouble(jTextField11.getText());
        double timeRemaining = Double.parseDouble(jTextField12.getText());
        double oldInterestRate = Double.parseDouble(jTextField13.getText())/100;
            
            // NEW Loan:
        double newLoanTerm = Double.parseDouble(jTextField4.getText());
        double newInterestRate = Double.parseDouble(jTextField5.getText())/100;
        double points = Double.parseDouble(jTextField6.getText());
        double costs = Double.parseDouble(jTextField7.getText());
        double cashOut = Double.parseDouble(jTextField9.getText());
        
        double amtLeft = refinanceHelper.findRemainingBal(originalLoan, loanTerm, timeRemaining , oldInterestRate);
        
        // find interest
        //double amtAfterInterest = originalLoan * Math.pow((1 + oldInterestRate), (loanTerm - timeRemaining));
        double amtAfterInterest = amtLeft * Math.pow((1 + oldInterestRate), (loanTerm - timeRemaining));
        double totInterest = amtAfterInterest - originalLoan;
        // calculate APR
        double formulaFrac = (totInterest + costs) / originalLoan;
        double APR = 100 * (formulaFrac / newLoanTerm);
        System.out.print("Amount after interest: "+ amtAfterInterest + '\n');
        System.out.print("total interest: "+ totInterest+ '\n');
        System.out.print("APR: "+ APR+ '\n');
        

        System.out.print("Amount Left :" + amtLeft);       
        double monthlyAmt = refinanceHelper.refinanceCalc(originalLoan, loanTerm, oldInterestRate);   // if this right, delete timeRemaining??  

        double diff = 100 * Math.abs(oldInterestRate - newInterestRate);
        double newMonthlyAmt = refinanceHelper.refinanceCalc((amtLeft + cashOut), newLoanTerm, newInterestRate);
        
        if (oldInterestRate < newInterestRate) {
            List<String> output = Arrays.asList("The APR for the new loan is", String.format("%.2f", APR), "- this is", String.valueOf(String.format("%.2f", diff) + "%"), "higher than the", String.format("%.2f", oldInterestRate), "interest rate of the current loan.");
            String joinedString = String.join(" ", output);
            jTextPane1.setText(joinedString);
            jTextField10.setText("financially MORE expensive.");
            jTextField8.setText(String.format("%.2f", newMonthlyAmt));
            
        } else if (oldInterestRate > newInterestRate) {
            List<String> output = Arrays.asList("The APR for the new loan is", String.format("%.2f", APR), "- this is", String.valueOf(String.format("%.2f", diff) + "%"), "lower than the", String.format("%.2f", oldInterestRate), "interest rate of the current loan.");
            String joinedString = String.join(" ", output);
            jTextPane1.setText(joinedString);
            jTextField10.setText("financially LESS expensive.");
            jTextField8.setText(String.format("%.2f", newMonthlyAmt));
        } else {
            List<String> output = Arrays.asList("The APR for the new loan is", String.format("%.2f", APR), "- this is equal to the", String.format("%.2f", oldInterestRate), "interest rate of the current loan.");
            String joinedString = String.join(" ", output);
            jTextPane1.setText(joinedString);
            jTextField10.setText("comparable in cost to the existing loan!");
            jTextField8.setText(String.format("%.2f", newMonthlyAmt));
        }    
        }
        
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField14ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextField14ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ComponentAdded

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel13.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel13.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(refinanceCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(refinanceCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(refinanceCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(refinanceCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new refinanceCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
