import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JTextField;
import javax.swing.*;
import java.awt.*; 
import java.text.DecimalFormat;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.text.NumberFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 5678m
 */
public class UpFrontHomePrice extends javax.swing.JFrame {

    /**
     * Creates new form UpFrontHomePrice
     */
    public UpFrontHomePrice() {
        initComponents();
        moneyPercentChoice.setSelectedIndex(0);
        upFrontHomeTitleLabel.setText("<html>Home Price And<br> Upfront Cash</html>");
        upFrontHomeTitleLabel.setHorizontalAlignment(resultLabel.CENTER);
        resultLabel.setHorizontalAlignment(resultLabel.CENTER);
        
        panelRound3.setBackground(new Color(66,133,244,80));
        jPanel3.setBackground(new Color(66,133,244,80));
        jPanel4.setBackground(new Color(66,133,244,80));
        
        calculateLabel.setHorizontalAlignment(calculateLabel.CENTER);
        closeLabel.setHorizontalAlignment(closeLabel.CENTER);
        clearFieldLabel.setHorizontalAlignment(clearFieldLabel.CENTER);
        
        imageLabel.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("images/CapitalLogo.png")).getImage().getScaledInstance(80,80,Image.SCALE_SMOOTH)));
        
        homePriceTextField.setBackground(new Color(66,133,244,80));
        cashAvailableTextField.setBackground(new Color(66,133,244,40));
        closingCostTextField.setBackground(new Color(66,133,244,80));
        interestRateTextField.setBackground(new Color(66,133,244,40));
        loanTermTextField.setBackground(new Color(66,133,244,80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        upFrontHomeTitleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        closingCost = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        homePriceTextField = new javax.swing.JTextField();
        cashAvailableTextField = new javax.swing.JTextField();
        closingCostTextField = new javax.swing.JTextField();
        interestRateTextField = new javax.swing.JTextField();
        loanTermTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        panelRound3 = new PanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        downPaymentLabel = new javax.swing.JLabel();
        downPaymentPercent = new javax.swing.JLabel();
        closingCostLabel = new javax.swing.JLabel();
        loanAmountLabel = new javax.swing.JLabel();
        monthlyPaymentLabel = new javax.swing.JLabel();
        moneyPercentChoice = new javax.swing.JComboBox<>();
        panelRound4 = new PanelRound();
        calculateLabel = new javax.swing.JLabel();
        panelRound5 = new PanelRound();
        clearFieldLabel = new javax.swing.JLabel();
        panelRound6 = new PanelRound();
        closeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1017, 689));

        jPanel2.setBackground(new java.awt.Color(66, 133, 244));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Capital Cal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(66, 133, 244));
        jPanel3.setForeground(new java.awt.Color(66, 133, 244));

        upFrontHomeTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        upFrontHomeTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        upFrontHomeTitleLabel.setText("Home Price");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upFrontHomeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upFrontHomeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Home Price ($):");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Cash Available ($):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Interest Rate (%):");

        closingCost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closingCost.setForeground(new java.awt.Color(102, 102, 102));
        closingCost.setText("Include Closing Cost:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Loan Term (Years):");

        homePriceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homePriceTextFieldKeyTyped(evt);
            }
        });

        cashAvailableTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashAvailableTextFieldKeyTyped(evt);
            }
        });

        closingCostTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                closingCostTextFieldKeyTyped(evt);
            }
        });

        interestRateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                interestRateTextFieldKeyTyped(evt);
            }
        });

        loanTermTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loanTermTextFieldKeyTyped(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(66, 133, 244));

        resultLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(255, 255, 255));
        resultLabel.setText("Results");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound3.setBackground(new java.awt.Color(66, 133, 244));
        panelRound3.setRoundButtomLeft(50);
        panelRound3.setRoundButtomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Down Payment:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Down Payment %:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Closing Cost:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Loan Amount:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Monthly Payment:");

        downPaymentLabel.setBackground(new java.awt.Color(255, 255, 255));
        downPaymentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        downPaymentLabel.setForeground(new java.awt.Color(102, 102, 102));
        downPaymentLabel.setOpaque(true);

        downPaymentPercent.setBackground(new java.awt.Color(255, 255, 255));
        downPaymentPercent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        downPaymentPercent.setForeground(new java.awt.Color(102, 102, 102));
        downPaymentPercent.setOpaque(true);

        closingCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        closingCostLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        closingCostLabel.setForeground(new java.awt.Color(102, 102, 102));
        closingCostLabel.setOpaque(true);

        loanAmountLabel.setBackground(new java.awt.Color(255, 255, 255));
        loanAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loanAmountLabel.setForeground(new java.awt.Color(102, 102, 102));
        loanAmountLabel.setOpaque(true);

        monthlyPaymentLabel.setBackground(new java.awt.Color(255, 255, 255));
        monthlyPaymentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthlyPaymentLabel.setForeground(new java.awt.Color(102, 102, 102));
        monthlyPaymentLabel.setOpaque(true);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(downPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(downPaymentPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closingCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loanAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthlyPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(downPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(downPaymentPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closingCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loanAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthlyPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );

        moneyPercentChoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        moneyPercentChoice.setForeground(new java.awt.Color(102, 102, 102));
        moneyPercentChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "%", "$" }));

        panelRound4.setBackground(new java.awt.Color(66, 133, 244));
        panelRound4.setRoundButtomLeft(25);
        panelRound4.setRoundButtomRight(25);
        panelRound4.setRoundTopLeft(25);
        panelRound4.setRoundTopRight(25);

        calculateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculateLabel.setForeground(new java.awt.Color(255, 255, 255));
        calculateLabel.setText("Calculate");
        calculateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound5.setBackground(new java.awt.Color(204, 204, 204));
        panelRound5.setRoundButtomLeft(25);
        panelRound5.setRoundButtomRight(25);
        panelRound5.setRoundTopLeft(25);
        panelRound5.setRoundTopRight(25);

        clearFieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearFieldLabel.setForeground(new java.awt.Color(255, 255, 255));
        clearFieldLabel.setText("Clear Fields");
        clearFieldLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearFieldLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearFieldLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearFieldLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound6.setBackground(new java.awt.Color(66, 133, 244));
        panelRound6.setRoundButtomLeft(25);
        panelRound6.setRoundButtomRight(25);
        panelRound6.setRoundTopLeft(25);
        panelRound6.setRoundTopRight(25);

        closeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setText("Close");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(closingCost)
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(closingCostTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(homePriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(cashAvailableTextField)))
                    .addComponent(interestRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(moneyPercentChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(homePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel2))
                                    .addComponent(cashAvailableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(closingCost)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(closingCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moneyPercentChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3))
                            .addComponent(interestRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(loanTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRound5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePriceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homePriceTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(homePriceTextField, evt);
    }//GEN-LAST:event_homePriceTextFieldKeyTyped

    private void cashAvailableTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashAvailableTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(cashAvailableTextField, evt);
    }//GEN-LAST:event_cashAvailableTextFieldKeyTyped

    private void closingCostTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closingCostTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(closingCostTextField, evt);
    }//GEN-LAST:event_closingCostTextFieldKeyTyped

    private void interestRateTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_interestRateTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(interestRateTextField, evt);
    }//GEN-LAST:event_interestRateTextFieldKeyTyped

    private void loanTermTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanTermTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateSingleInput(loanTermTextField, evt);
    }//GEN-LAST:event_loanTermTextFieldKeyTyped

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void clearFieldLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldLabelMouseClicked
        // TODO add your handling code here:
        homePriceTextField.setText("");
        cashAvailableTextField.setText("");
        closingCostTextField.setText("");
        interestRateTextField.setText("");
        loanTermTextField.setText("");
    }//GEN-LAST:event_clearFieldLabelMouseClicked

    private void calculateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateLabelMouseClicked
        // TODO add your handling code here:
        String homePriceStr = homePriceTextField.getText().trim();
        String cashAvailableStr = cashAvailableTextField.getText().trim();
        String closingCostStr = closingCostTextField.getText().trim();
        String interestRateStr = interestRateTextField.getText().trim();
        String loanTermStr = loanTermTextField.getText().trim();
        
        if(!Helper.upFrontHomePriceValidation(homePriceStr, cashAvailableStr, closingCostStr, interestRateStr, loanTermStr)){
            homePriceTextField.requestFocus();
            return;
        }
        
        double homePriceNum = Double.parseDouble(homePriceTextField.getText());
        double cashAvailableNum = Double.parseDouble(cashAvailableTextField.getText());
        double closingCostNum = Double.parseDouble(closingCostTextField.getText());
        double interestRateNum = Double.parseDouble(interestRateTextField.getText());
        int loanTermNum = Integer.parseInt(loanTermTextField.getText());
        double[] totalMoney;
        
        if(moneyPercentChoice.getSelectedIndex() == 0){
            if(closingCost.isSelected()){
                if(closingCostNum >= 100){
                    JOptionPane.showMessageDialog(null, "Closing cost can not be greater then or equal to 100%!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                    homePriceTextField.requestFocus();
                    return;
                }
            }
            if(closingCost.isSelected()){
                totalMoney = Helper.upFrontHomePriceWithCloseCostPercent(homePriceNum, cashAvailableNum, closingCostNum, interestRateNum, loanTermNum);
                for (double value : totalMoney) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        homePriceTextField.requestFocus();
                        return;
                    }
                }
                
                double totalDownPayment = totalMoney[0];
                double totalDownPercent = totalMoney[1];
                double totalClosingCost = totalMoney[2];
                double totalLoanAmount = totalMoney[3];
                double totalMonthlyPayment = totalMoney[4];
                
                DecimalFormat formatter = new DecimalFormat("#,###.00");
                downPaymentLabel.setText("$" + formatter.format(totalDownPayment));
                closingCostLabel.setText("$" + formatter.format(totalClosingCost));
                loanAmountLabel.setText("$" + formatter.format(totalLoanAmount));
                monthlyPaymentLabel.setText("$" + formatter.format(totalMonthlyPayment));
                downPaymentPercent.setText(formatter.format(totalDownPercent) + "%"); 
               
            }else{
                totalMoney = Helper.upFrontHomePriceWithoutCloseCostPercent(homePriceNum, cashAvailableNum, interestRateNum, loanTermNum);
                for (double value : totalMoney) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        homePriceTextField.requestFocus();
                        return;
                    }
                }
                
                double totalDownPayment = totalMoney[0];
                double totalDownPercent = totalMoney[1];
                double totalClosingCost = 0;
                double totalLoanAmount = totalMoney[2];
                double totalMonthlyPayment = totalMoney[3];
                
                DecimalFormat formatter = new DecimalFormat("#,###.00");
                downPaymentLabel.setText("$" + formatter.format(totalDownPayment));
                closingCostLabel.setText("$" + formatter.format(totalClosingCost));
                loanAmountLabel.setText("$" + formatter.format(totalLoanAmount));
                monthlyPaymentLabel.setText("$" + formatter.format(totalMonthlyPayment));
                downPaymentPercent.setText(formatter.format(totalDownPercent) + "%");
                
            }
        }else{
            if(closingCost.isSelected()){
                
                totalMoney = Helper.upFrontHomePriceWithCloseCostMoney(homePriceNum, cashAvailableNum, closingCostNum, interestRateNum, loanTermNum);
                for (double value : totalMoney) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        homePriceTextField.requestFocus();
                        return;
                    }
                }
                
                
                double totalDownPayment = totalMoney[0];
                double totalDownPercent = totalMoney[1];
                double totalClosingCost = totalMoney[2];
                double totalLoanAmount = totalMoney[3];
                double totalMonthlyPayment = totalMoney[4];
                
                DecimalFormat formatter = new DecimalFormat("#,###.00");
                downPaymentLabel.setText("$" + formatter.format(totalDownPayment));
                closingCostLabel.setText("$" + formatter.format(totalClosingCost));
                loanAmountLabel.setText("$" + formatter.format(totalLoanAmount));
                monthlyPaymentLabel.setText("$" + formatter.format(totalMonthlyPayment));
                downPaymentPercent.setText(formatter.format(totalDownPercent) + "%");
                
            }else{
                totalMoney = Helper.upFrontHomePriceWithoutCloseCostMoney(homePriceNum, cashAvailableNum, interestRateNum, loanTermNum);
                for (double value : totalMoney) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        homePriceTextField.requestFocus();
                        return;
                    }
                }
                
                double totalDownPayment = totalMoney[0];
                double totalDownPercent = totalMoney[1];
                double totalClosingCost = 0;
                double totalLoanAmount = totalMoney[2];
                double totalMonthlyPayment = totalMoney[3];
                
                DecimalFormat formatter = new DecimalFormat("#,###.00");
                downPaymentLabel.setText("$" + formatter.format(totalDownPayment));
                closingCostLabel.setText("$" + formatter.format(totalClosingCost));
                loanAmountLabel.setText("$" + formatter.format(totalLoanAmount));
                monthlyPaymentLabel.setText("$" + formatter.format(totalMonthlyPayment));
                downPaymentPercent.setText(formatter.format(totalDownPercent) + "%");
                
            }
        }
    }//GEN-LAST:event_calculateLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpFrontHomePrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpFrontHomePrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpFrontHomePrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpFrontHomePrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpFrontHomePrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calculateLabel;
    private javax.swing.JTextField cashAvailableTextField;
    private javax.swing.JLabel clearFieldLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JCheckBox closingCost;
    private javax.swing.JLabel closingCostLabel;
    private javax.swing.JTextField closingCostTextField;
    private javax.swing.JLabel downPaymentLabel;
    private javax.swing.JLabel downPaymentPercent;
    private javax.swing.JTextField homePriceTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField interestRateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel loanAmountLabel;
    private javax.swing.JTextField loanTermTextField;
    private javax.swing.JComboBox<String> moneyPercentChoice;
    private javax.swing.JLabel monthlyPaymentLabel;
    private PanelRound panelRound1;
    private PanelRound panelRound2;
    private PanelRound panelRound3;
    private PanelRound panelRound4;
    private PanelRound panelRound5;
    private PanelRound panelRound6;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel upFrontHomeTitleLabel;
    // End of variables declaration//GEN-END:variables
}
