import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JTextField;
import javax.swing.*;
import java.awt.*; 
import java.text.DecimalFormat;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 5678m
 */
public class UpFrontCashCalculator extends javax.swing.JFrame {

    /**
     * Creates new form UpFrontCashCalculator
     */
    public UpFrontCashCalculator() {
        initComponents();
        titleLabel.setHorizontalAlignment(titleLabel.CENTER);
        calculateLabel.setHorizontalAlignment(calculateLabel.CENTER);
        clearFieldsLabel.setHorizontalAlignment(clearFieldsLabel.CENTER);
        resultLabel.setHorizontalAlignment(resultLabel.CENTER);
        closeLabel.setHorizontalAlignment(closeLabel.CENTER);
        
        panelRound3.setBackground(new Color(66,133,244,80));
        jPanel3.setBackground(new Color(66,133,244,80));
        jPanel4.setBackground(new Color(66,133,244,80));
        upFrontCashTextField.setBackground(new Color(66,133,244,80));
        downPaymentTextField.setBackground(new Color(66,133,244,40));
        closingCostTextField.setBackground(new Color(66,133,244,80));
        interestRateTextField.setBackground(new Color(66,133,244,40));
        loanTermTextField.setBackground(new Color(66,133,244,80));
        
        imageLabel.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("images/CapitalLogo.png")).getImage().getScaledInstance(80,80,Image.SCALE_SMOOTH)));

        
        moneyPercentChange.setSelectedIndex(0); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        upfrontCashLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        downPaymentLabel = new javax.swing.JLabel();
        closingCost = new javax.swing.JCheckBox();
        interestRateLabel = new javax.swing.JLabel();
        loanTermLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        upFrontCashTextField = new javax.swing.JTextField();
        downPaymentTextField = new javax.swing.JTextField();
        closingCostTextField = new javax.swing.JTextField();
        interestRateTextField = new javax.swing.JTextField();
        loanTermTextField = new javax.swing.JTextField();
        panelRound1 = new PanelRound();
        calculateLabel = new javax.swing.JLabel();
        panelRound2 = new PanelRound();
        clearFieldsLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        panelRound3 = new PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        homePriceLabel = new javax.swing.JLabel();
        downPayLabel = new javax.swing.JLabel();
        closingCostLabel = new javax.swing.JLabel();
        loanAmountLabel = new javax.swing.JLabel();
        monthlyPaymentLabel = new javax.swing.JLabel();
        panelRound4 = new PanelRound();
        closeLabel = new javax.swing.JLabel();
        moneyPercentChange = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        upfrontCashLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        upfrontCashLabel.setForeground(new java.awt.Color(102, 102, 102));
        upfrontCashLabel.setText("UpFront Cash Available ($):");

        jPanel2.setBackground(new java.awt.Color(66, 133, 244));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Capital Cal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        downPaymentLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        downPaymentLabel.setForeground(new java.awt.Color(102, 102, 102));
        downPaymentLabel.setText("Down Payment (%):");

        closingCost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closingCost.setForeground(new java.awt.Color(102, 102, 102));
        closingCost.setText("Include Closing Cost:");

        interestRateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        interestRateLabel.setForeground(new java.awt.Color(102, 102, 102));
        interestRateLabel.setText("Interest Rate (%):");

        loanTermLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loanTermLabel.setForeground(new java.awt.Color(102, 102, 102));
        loanTermLabel.setText("Loan Term (Years):");

        jPanel3.setBackground(new java.awt.Color(66, 133, 244));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Upfront Cash Available");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        upFrontCashTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                upFrontCashTextFieldKeyTyped(evt);
            }
        });

        downPaymentTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                downPaymentTextFieldKeyTyped(evt);
            }
        });

        closingCostTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                closingCostTextFieldKeyTyped(evt);
            }
        });

        interestRateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                interestRateTextFieldKeyTyped(evt);
            }
        });

        loanTermTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loanTermTextFieldKeyTyped(evt);
            }
        });

        panelRound1.setBackground(new java.awt.Color(66, 133, 244));
        panelRound1.setRoundButtomLeft(25);
        panelRound1.setRoundButtomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);

        calculateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculateLabel.setForeground(new java.awt.Color(255, 255, 255));
        calculateLabel.setText("Calculate");
        calculateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound2.setBackground(new java.awt.Color(204, 204, 204));
        panelRound2.setRoundButtomLeft(25);
        panelRound2.setRoundButtomRight(25);
        panelRound2.setRoundTopLeft(25);
        panelRound2.setRoundTopRight(25);

        clearFieldsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearFieldsLabel.setForeground(new java.awt.Color(255, 255, 255));
        clearFieldsLabel.setText("Clear Fields");
        clearFieldsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearFieldsLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearFieldsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearFieldsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(66, 133, 244));

        resultLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(255, 255, 255));
        resultLabel.setText("Results");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound3.setBackground(new java.awt.Color(66, 133, 244));
        panelRound3.setRoundButtomLeft(50);
        panelRound3.setRoundButtomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Home Price:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Down Payment:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Closing Cost:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Loan Amount:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Monthly Payment:");

        homePriceLabel.setBackground(new java.awt.Color(255, 255, 255));
        homePriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homePriceLabel.setForeground(new java.awt.Color(102, 102, 102));
        homePriceLabel.setOpaque(true);

        downPayLabel.setBackground(new java.awt.Color(255, 255, 255));
        downPayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        downPayLabel.setForeground(new java.awt.Color(102, 102, 102));
        downPayLabel.setToolTipText("");
        downPayLabel.setOpaque(true);

        closingCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        closingCostLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closingCostLabel.setForeground(new java.awt.Color(102, 102, 102));
        closingCostLabel.setOpaque(true);

        loanAmountLabel.setBackground(new java.awt.Color(255, 255, 255));
        loanAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loanAmountLabel.setForeground(new java.awt.Color(102, 102, 102));
        loanAmountLabel.setOpaque(true);

        monthlyPaymentLabel.setBackground(new java.awt.Color(255, 255, 255));
        monthlyPaymentLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        monthlyPaymentLabel.setForeground(new java.awt.Color(102, 102, 102));
        monthlyPaymentLabel.setOpaque(true);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homePriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(downPayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closingCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loanAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthlyPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(homePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(downPayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(closingCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(loanAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(monthlyPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        panelRound4.setBackground(new java.awt.Color(66, 133, 244));
        panelRound4.setRoundButtomLeft(25);
        panelRound4.setRoundButtomRight(25);
        panelRound4.setRoundTopLeft(25);
        panelRound4.setRoundTopRight(25);

        closeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setText("Close");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        moneyPercentChange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        moneyPercentChange.setForeground(new java.awt.Color(102, 102, 102));
        moneyPercentChange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "%", "$" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(closingCost)
                                    .addComponent(interestRateLabel)
                                    .addComponent(loanTermLabel)
                                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(loanTermTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(interestRateTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(closingCostTextField))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moneyPercentChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(upfrontCashLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(downPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(upFrontCashTextField)
                                    .addComponent(downPaymentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upfrontCashLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(upFrontCashTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downPaymentLabel)
                            .addComponent(downPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(closingCost)
                            .addComponent(closingCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moneyPercentChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(interestRateLabel)
                            .addComponent(interestRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loanTermLabel)
                            .addComponent(loanTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void upFrontCashTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_upFrontCashTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(upFrontCashTextField, evt);
    }//GEN-LAST:event_upFrontCashTextFieldKeyTyped

    private void downPaymentTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_downPaymentTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(downPaymentTextField, evt);
    }//GEN-LAST:event_downPaymentTextFieldKeyTyped

    private void closingCostTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closingCostTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(closingCostTextField, evt);
    }//GEN-LAST:event_closingCostTextFieldKeyTyped

    private void interestRateTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_interestRateTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateDoubleInput(interestRateTextField, evt);
    }//GEN-LAST:event_interestRateTextFieldKeyTyped

    private void loanTermTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanTermTextFieldKeyTyped
        // TODO add your handling code here:
        Helper.validateSingleInput(loanTermTextField, evt);
    }//GEN-LAST:event_loanTermTextFieldKeyTyped

    private void calculateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateLabelMouseClicked
        // TODO add your handling code here:
        String upFrontCashStr = upFrontCashTextField.getText().trim();
        String downPaymentStr = downPaymentTextField.getText().trim();
        String closingCostStr = closingCostTextField.getText().trim();
        String interestRateStr = interestRateTextField.getText().trim();
        String loanTermStr = loanTermTextField.getText().trim();
        
        if(!Helper.downPaymentUpFrontValidatoin(upFrontCashStr,downPaymentStr, closingCostStr, interestRateStr, loanTermStr)){
            upFrontCashTextField.requestFocus();
            return;
        }
        double upFrontCashNum = Double.parseDouble(upFrontCashTextField.getText());
        double downPaymentNum = Double.parseDouble(downPaymentTextField.getText());
        double closingCostNum = Double.parseDouble(closingCostTextField.getText());
        double interestRateNum = Double.parseDouble(interestRateTextField.getText());
        int loanTermNum = Integer.parseInt(loanTermTextField.getText());
        double[] totalMoney;
        
        if(moneyPercentChange.getSelectedIndex() == 0){
            if(closingCost.isSelected()){
                if(closingCostNum >= 100){
                    JOptionPane.showMessageDialog(null, "Closing cost can not be greater then or equal to 100%!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                    upFrontCashTextField.requestFocus();
                    return;
                }
                totalMoney = Helper.upFrontCashWithClosingCostPercent(upFrontCashNum, downPaymentNum, closingCostNum, interestRateNum, loanTermNum);
                for (double value : totalMoney) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        upFrontCashTextField.requestFocus();
                        return;
                    }
                }
                
                
                double totalHomePrice = totalMoney[0];
                double totalDownPayment = totalMoney[1];
                double totalCloseCost = totalMoney[2];
                double totalLoanAmount = totalMoney[3];
                double totalMonthlyPayment = totalMoney[4];
                
                DecimalFormat formatter = new DecimalFormat("#,###.00");
                homePriceLabel.setText("$" + formatter.format(totalHomePrice));
                downPayLabel.setText("$" + formatter.format(totalDownPayment));
                closingCostLabel.setText("$" + formatter.format(totalCloseCost));
                loanAmountLabel.setText("$" + formatter.format(totalLoanAmount));
                monthlyPaymentLabel.setText("$" + formatter.format(totalMonthlyPayment));
                
            }else{
                totalMoney = Helper.upFrontCashWithOutClosingCostPercent(upFrontCashNum, downPaymentNum, interestRateNum, loanTermNum);
                for (double value : totalMoney) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        upFrontCashTextField.requestFocus();
                        return;
                    }
                }
                
                double totalHomePrice = totalMoney[0];
                double totalDownPayment = totalMoney[1];
                double totalLoanAmount = totalMoney[2];
                double totalMonthlyPayment = totalMoney[3];
                double totalCloseCost = 0;
                
                DecimalFormat formatter = new DecimalFormat("#,###.00");
                homePriceLabel.setText("$" + formatter.format(totalHomePrice));
                downPayLabel.setText("$" + formatter.format(totalDownPayment));
                closingCostLabel.setText("$" + totalCloseCost);
                loanAmountLabel.setText("$" + formatter.format(totalLoanAmount));
                monthlyPaymentLabel.setText("$" + formatter.format(totalMonthlyPayment));
            }
        }else{
            if(closingCost.isSelected()){
                if(closingCostNum > upFrontCashNum){
                    JOptionPane.showMessageDialog(null, "Closing cost can not be greater then upfront cash available!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                    upFrontCashTextField.requestFocus();
                    return;
                }
                
                totalMoney = Helper.upFrontCashWithClosingCostMoney(upFrontCashNum, downPaymentNum, closingCostNum, interestRateNum, loanTermNum);
                for (double value : totalMoney) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        upFrontCashTextField.requestFocus();
                        return;
                    }
                }
                
                double totalHomePrice = totalMoney[0];
                double totalDownPayment = totalMoney[1];
                double totalCloseCost = totalMoney[2];
                double totalLoanAmount = totalMoney[3];
                double totalMonthlyPayment = totalMoney[4];
                
                DecimalFormat formatter = new DecimalFormat("#,###.00");
                homePriceLabel.setText("$" + formatter.format(totalHomePrice));
                downPayLabel.setText("$" + formatter.format(totalDownPayment));
                closingCostLabel.setText("$" + formatter.format(totalCloseCost));
                loanAmountLabel.setText("$" + formatter.format(totalLoanAmount));
                monthlyPaymentLabel.setText("$" + formatter.format(totalMonthlyPayment));
            }else{
                totalMoney = Helper.upFrontCashWithOutClosingCostMoney(upFrontCashNum, downPaymentNum, interestRateNum, loanTermNum);
                for (double value : totalMoney) {
                    if (value < 0) {
                        JOptionPane.showMessageDialog(null, "One or more calculated values are negative. Please check your inputs!", "Calculation Error", JOptionPane.ERROR_MESSAGE);
                        upFrontCashTextField.requestFocus();
                        return;
                    }
                }
                
                double totalHomePrice = totalMoney[0];
                double totalDownPayment = totalMoney[1];
                double totalLoanAmount = totalMoney[2];
                double totalMonthlyPayment = totalMoney[3];
                double totalCloseCost = 0;
                
                DecimalFormat formatter = new DecimalFormat("#,###.00");
                homePriceLabel.setText("$" + formatter.format(totalHomePrice));
                downPayLabel.setText("$" + formatter.format(totalDownPayment));
                closingCostLabel.setText("$" + totalCloseCost);
                loanAmountLabel.setText("$" + formatter.format(totalLoanAmount));
                monthlyPaymentLabel.setText("$" + formatter.format(totalMonthlyPayment));
            }
        }
    }//GEN-LAST:event_calculateLabelMouseClicked

    private void clearFieldsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldsLabelMouseClicked
        // TODO add your handling code here:
        upFrontCashTextField.setText("");
        downPaymentTextField.setText("");
        closingCostTextField.setText("");
        interestRateTextField.setText("");
        loanTermTextField.setText("");
        upFrontCashTextField.requestFocus();
    }//GEN-LAST:event_clearFieldsLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpFrontCashCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpFrontCashCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpFrontCashCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpFrontCashCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpFrontCashCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calculateLabel;
    private javax.swing.JLabel clearFieldsLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JCheckBox closingCost;
    private javax.swing.JLabel closingCostLabel;
    private javax.swing.JTextField closingCostTextField;
    private javax.swing.JLabel downPayLabel;
    private javax.swing.JLabel downPaymentLabel;
    private javax.swing.JTextField downPaymentTextField;
    private javax.swing.JLabel homePriceLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel interestRateLabel;
    private javax.swing.JTextField interestRateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel loanAmountLabel;
    private javax.swing.JLabel loanTermLabel;
    private javax.swing.JTextField loanTermTextField;
    private javax.swing.JComboBox<String> moneyPercentChange;
    private javax.swing.JLabel monthlyPaymentLabel;
    private PanelRound panelRound1;
    private PanelRound panelRound2;
    private PanelRound panelRound3;
    private PanelRound panelRound4;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField upFrontCashTextField;
    private javax.swing.JLabel upfrontCashLabel;
    // End of variables declaration//GEN-END:variables
}
